module OnebusawaySDK
  module Models
    type agencies_with_coverage_list_params =
      {  } & OnebusawaySDK::request_parameters

    class AgenciesWithCoverageListParams < OnebusawaySDK::BaseModel
      extend OnebusawaySDK::Type::RequestParameters::Converter
      include OnebusawaySDK::RequestParameters

      def initialize: (?request_options: OnebusawaySDK::request_opts) -> void

      def to_hash: -> OnebusawaySDK::Models::agencies_with_coverage_list_params
    end
  end
end
