module OnebusawaySDK
  module Models
    type agencies_with_coverage_list_response =
      { data: OnebusawaySDK::Models::AgenciesWithCoverageListResponse::Data }

    class AgenciesWithCoverageListResponse < OnebusawaySDK::Models::ResponseWrapper
      def data: -> OnebusawaySDK::Models::AgenciesWithCoverageListResponse::Data

      def data=: (
        OnebusawaySDK::Models::AgenciesWithCoverageListResponse::Data _
      ) -> OnebusawaySDK::Models::AgenciesWithCoverageListResponse::Data

      def initialize: (
        data: OnebusawaySDK::Models::AgenciesWithCoverageListResponse::Data
      ) -> void

      def to_hash: -> OnebusawaySDK::Models::agencies_with_coverage_list_response

      type data =
        {
          limit_exceeded: bool,
          list: ::Array[OnebusawaySDK::Models::AgenciesWithCoverageListResponse::Data::List],
          references: OnebusawaySDK::Models::References
        }

      class Data < OnebusawaySDK::Internal::Type::BaseModel
        attr_accessor limit_exceeded: bool

        attr_accessor list: ::Array[OnebusawaySDK::Models::AgenciesWithCoverageListResponse::Data::List]

        attr_accessor references: OnebusawaySDK::Models::References

        def initialize: (
          limit_exceeded: bool,
          list: ::Array[OnebusawaySDK::Models::AgenciesWithCoverageListResponse::Data::List],
          references: OnebusawaySDK::Models::References
        ) -> void

        def to_hash: -> OnebusawaySDK::Models::AgenciesWithCoverageListResponse::data

        type list =
          {
            agency_id: String,
            lat: Float,
            lat_span: Float,
            lon: Float,
            lon_span: Float
          }

        class List < OnebusawaySDK::Internal::Type::BaseModel
          attr_accessor agency_id: String

          attr_accessor lat: Float

          attr_accessor lat_span: Float

          attr_accessor lon: Float

          attr_accessor lon_span: Float

          def initialize: (
            agency_id: String,
            lat: Float,
            lat_span: Float,
            lon: Float,
            lon_span: Float
          ) -> void

          def to_hash: -> OnebusawaySDK::Models::AgenciesWithCoverageListResponse::Data::list
        end
      end
    end
  end
end
