module OnebusawaySDK
  module Models
    type arrival_and_departure_list_params =
      { minutes_after: Integer, minutes_before: Integer, time: Time }
      & OnebusawaySDK::Internal::Type::request_parameters

    class ArrivalAndDepartureListParams < OnebusawaySDK::Internal::Type::BaseModel
      extend OnebusawaySDK::Internal::Type::RequestParameters::Converter
      include OnebusawaySDK::Internal::Type::RequestParameters

      attr_reader minutes_after: Integer?

      def minutes_after=: (Integer) -> Integer

      attr_reader minutes_before: Integer?

      def minutes_before=: (Integer) -> Integer

      attr_reader time: Time?

      def time=: (Time) -> Time

      def initialize: (
        ?minutes_after: Integer,
        ?minutes_before: Integer,
        ?time: Time,
        ?request_options: OnebusawaySDK::request_opts
      ) -> void

      def to_hash: -> OnebusawaySDK::Models::arrival_and_departure_list_params
    end
  end
end
