module OnebusawaySDK
  module Models
    type current_time_retrieve_params =
      {  } & OnebusawaySDK::Internal::Type::request_parameters

    class CurrentTimeRetrieveParams < OnebusawaySDK::Internal::Type::BaseModel
      extend OnebusawaySDK::Internal::Type::RequestParameters::Converter
      include OnebusawaySDK::Internal::Type::RequestParameters

      def initialize: (?request_options: OnebusawaySDK::request_opts) -> void

      def to_hash: -> { request_options: OnebusawaySDK::RequestOptions }
    end
  end
end
