module OnebusawaySDK
  module Models
    type route_ids_for_agency_list_response =
      { data: OnebusawaySDK::Models::RouteIDsForAgencyListResponse::Data }

    class RouteIDsForAgencyListResponse < OnebusawaySDK::Models::ResponseWrapper
      def data: -> OnebusawaySDK::Models::RouteIDsForAgencyListResponse::Data

      def data=: (
        OnebusawaySDK::Models::RouteIDsForAgencyListResponse::Data _
      ) -> OnebusawaySDK::Models::RouteIDsForAgencyListResponse::Data

      def initialize: (
        data: OnebusawaySDK::Models::RouteIDsForAgencyListResponse::Data
      ) -> void

      def to_hash: -> OnebusawaySDK::Models::route_ids_for_agency_list_response

      type data =
        {
          limit_exceeded: bool,
          list: ::Array[String],
          references: OnebusawaySDK::Models::References
        }

      class Data < OnebusawaySDK::Internal::Type::BaseModel
        attr_accessor limit_exceeded: bool

        attr_accessor list: ::Array[String]

        attr_accessor references: OnebusawaySDK::Models::References

        def initialize: (
          limit_exceeded: bool,
          list: ::Array[String],
          references: OnebusawaySDK::Models::References
        ) -> void

        def to_hash: -> OnebusawaySDK::Models::RouteIDsForAgencyListResponse::data
      end
    end
  end
end
