module OnebusawaySDK
  module Models
    type route_ids_for_agency_list_params =
      {  } & OnebusawaySDK::Internal::Type::request_parameters

    class RouteIDsForAgencyListParams < OnebusawaySDK::Internal::Type::BaseModel
      extend OnebusawaySDK::Internal::Type::RequestParameters::Converter
      include OnebusawaySDK::Internal::Type::RequestParameters

      def initialize: (?request_options: OnebusawaySDK::request_opts) -> void
    end
  end
end
