module OnebusawaySDK
  module Models
    type route_retrieve_params =
      { route_id: String } & OnebusawaySDK::Internal::Type::request_parameters

    class RouteRetrieveParams < OnebusawaySDK::Internal::Type::BaseModel
      extend OnebusawaySDK::Internal::Type::RequestParameters::Converter
      include OnebusawaySDK::Internal::Type::RequestParameters

      attr_accessor route_id: String

      def initialize: (
        route_id: String,
        ?request_options: OnebusawaySDK::request_opts
      ) -> void

      def to_hash: -> {
        route_id: String,
        request_options: OnebusawaySDK::RequestOptions
      }
    end
  end
end
