module OnebusawaySDK
  module Models
    type route_retrieve_response =
      { data: OnebusawaySDK::Models::RouteRetrieveResponse::Data }

    class RouteRetrieveResponse < OnebusawaySDK::Models::ResponseWrapper
      def data: -> OnebusawaySDK::Models::RouteRetrieveResponse::Data

      def data=: (
        OnebusawaySDK::Models::RouteRetrieveResponse::Data _
      ) -> OnebusawaySDK::Models::RouteRetrieveResponse::Data

      def initialize: (
        data: OnebusawaySDK::Models::RouteRetrieveResponse::Data
      ) -> void

      type data =
        {
          entry: OnebusawaySDK::Models::RouteRetrieveResponse::Data::Entry,
          references: OnebusawaySDK::References
        }

      class Data < OnebusawaySDK::Internal::Type::BaseModel
        attr_accessor entry: OnebusawaySDK::Models::RouteRetrieveResponse::Data::Entry

        attr_accessor references: OnebusawaySDK::References

        def initialize: (
          entry: OnebusawaySDK::Models::RouteRetrieveResponse::Data::Entry,
          references: OnebusawaySDK::References
        ) -> void

        type entry =
          {
            id: String,
            agency_id: String,
            type: Integer,
            color: String,
            description: String,
            long_name: String,
            null_safe_short_name: String,
            short_name: String,
            text_color: String,
            url: String
          }

        class Entry < OnebusawaySDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor agency_id: String

          attr_accessor type: Integer

          attr_reader color: String?

          def color=: (String) -> String

          attr_reader description: String?

          def description=: (String) -> String

          attr_reader long_name: String?

          def long_name=: (String) -> String

          attr_reader null_safe_short_name: String?

          def null_safe_short_name=: (String) -> String

          attr_reader short_name: String?

          def short_name=: (String) -> String

          attr_reader text_color: String?

          def text_color=: (String) -> String

          attr_reader url: String?

          def url=: (String) -> String

          def initialize: (
            id: String,
            agency_id: String,
            type: Integer,
            ?color: String,
            ?description: String,
            ?long_name: String,
            ?null_safe_short_name: String,
            ?short_name: String,
            ?text_color: String,
            ?url: String
          ) -> void
        end
      end
    end
  end
end
