module OnebusawaySDK
  module Models
    type route_ids_for_agency_list_response =
      { data: OnebusawaySDK::Models::RouteIDsForAgencyListResponse::Data }

    class RouteIDsForAgencyListResponse < OnebusawaySDK::Models::ResponseWrapper
      def data: -> OnebusawaySDK::Models::RouteIDsForAgencyListResponse::Data

      def data=: (
        OnebusawaySDK::Models::RouteIDsForAgencyListResponse::Data _
      ) -> OnebusawaySDK::Models::RouteIDsForAgencyListResponse::Data

      def initialize: (
        data: OnebusawaySDK::Models::RouteIDsForAgencyListResponse::Data
      ) -> void

      def to_hash: -> {
        data: OnebusawaySDK::Models::RouteIDsForAgencyListResponse::Data
      }

      type data =
        {
          list: ::Array[String],
          references: OnebusawaySDK::References,
          limit_exceeded: bool
        }

      class Data < OnebusawaySDK::Internal::Type::BaseModel
        attr_accessor list: ::Array[String]

        attr_accessor references: OnebusawaySDK::References

        attr_reader limit_exceeded: bool?

        def limit_exceeded=: (bool) -> bool

        def initialize: (
          list: ::Array[String],
          references: OnebusawaySDK::References,
          ?limit_exceeded: bool
        ) -> void

        def to_hash: -> {
          list: ::Array[String],
          references: OnebusawaySDK::References,
          limit_exceeded: bool
        }
      end
    end
  end
end
