module OnebusawaySDK
  module Models
    type schedule_for_route_retrieve_params =
      { date: Date } & OnebusawaySDK::Internal::Type::request_parameters

    class ScheduleForRouteRetrieveParams < OnebusawaySDK::Internal::Type::BaseModel
      extend OnebusawaySDK::Internal::Type::RequestParameters::Converter
      include OnebusawaySDK::Internal::Type::RequestParameters

      attr_reader date: Date?

      def date=: (Date) -> Date

      def initialize: (
        ?date: Date,
        ?request_options: OnebusawaySDK::request_opts
      ) -> void

      def to_hash: -> {
        date: Date,
        request_options: OnebusawaySDK::RequestOptions
      }
    end
  end
end
