module OnebusawaySDK
  module Models
    type schedule_for_stop_retrieve_params =
      { date: Date } & OnebusawaySDK::Internal::Type::request_parameters

    class ScheduleForStopRetrieveParams < OnebusawaySDK::Internal::Type::BaseModel
      extend OnebusawaySDK::Internal::Type::RequestParameters::Converter
      include OnebusawaySDK::Internal::Type::RequestParameters

      attr_reader date: Date?

      def date=: (Date) -> Date

      def initialize: (
        ?date: Date,
        ?request_options: OnebusawaySDK::request_opts
      ) -> void

      def to_hash: -> OnebusawaySDK::Models::schedule_for_stop_retrieve_params
    end
  end
end
