module OnebusawaySDK
  module Models
    type schedule_for_route_retrieve_response =
      { data: OnebusawaySDK::Models::ScheduleForRouteRetrieveResponse::Data }

    class ScheduleForRouteRetrieveResponse < OnebusawaySDK::Models::ResponseWrapper
      def data: -> OnebusawaySDK::Models::ScheduleForRouteRetrieveResponse::Data

      def data=: (
        OnebusawaySDK::Models::ScheduleForRouteRetrieveResponse::Data _
      ) -> OnebusawaySDK::Models::ScheduleForRouteRetrieveResponse::Data

      def initialize: (
        data: OnebusawaySDK::Models::ScheduleForRouteRetrieveResponse::Data
      ) -> void

      def to_hash: -> {
        data: OnebusawaySDK::Models::ScheduleForRouteRetrieveResponse::Data
      }

      type data =
        {
          entry: OnebusawaySDK::Models::ScheduleForRouteRetrieveResponse::Data::Entry
        }

      class Data < OnebusawaySDK::Internal::Type::BaseModel
        attr_accessor entry: OnebusawaySDK::Models::ScheduleForRouteRetrieveResponse::Data::Entry

        def initialize: (
          entry: OnebusawaySDK::Models::ScheduleForRouteRetrieveResponse::Data::Entry
        ) -> void

        def to_hash: -> {
          entry: OnebusawaySDK::Models::ScheduleForRouteRetrieveResponse::Data::Entry
        }

        type entry =
          {
            route_id: String,
            schedule_date: Integer,
            service_ids: ::Array[String],
            stop_trip_groupings: ::Array[OnebusawaySDK::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping]
          }

        class Entry < OnebusawaySDK::Internal::Type::BaseModel
          attr_accessor route_id: String

          attr_accessor schedule_date: Integer

          attr_accessor service_ids: ::Array[String]

          attr_accessor stop_trip_groupings: ::Array[OnebusawaySDK::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping]

          def initialize: (
            route_id: String,
            schedule_date: Integer,
            service_ids: ::Array[String],
            stop_trip_groupings: ::Array[OnebusawaySDK::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping]
          ) -> void

          def to_hash: -> {
            route_id: String,
            schedule_date: Integer,
            service_ids: ::Array[String],
            stop_trip_groupings: ::Array[OnebusawaySDK::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping]
          }

          type stop_trip_grouping =
            {
              direction_id: String,
              stop_ids: ::Array[String],
              trip_headsigns: ::Array[String],
              trip_ids: ::Array[String],
              trips_with_stop_times: ::Array[OnebusawaySDK::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping::TripsWithStopTime]
            }

          class StopTripGrouping < OnebusawaySDK::Internal::Type::BaseModel
            attr_accessor direction_id: String

            attr_accessor stop_ids: ::Array[String]

            attr_accessor trip_headsigns: ::Array[String]

            attr_accessor trip_ids: ::Array[String]

            attr_reader trips_with_stop_times: ::Array[OnebusawaySDK::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping::TripsWithStopTime]?

            def trips_with_stop_times=: (
              ::Array[OnebusawaySDK::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping::TripsWithStopTime]
            ) -> ::Array[OnebusawaySDK::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping::TripsWithStopTime]

            def initialize: (
              direction_id: String,
              stop_ids: ::Array[String],
              trip_headsigns: ::Array[String],
              trip_ids: ::Array[String],
              ?trips_with_stop_times: ::Array[OnebusawaySDK::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping::TripsWithStopTime]
            ) -> void

            def to_hash: -> {
              direction_id: String,
              stop_ids: ::Array[String],
              trip_headsigns: ::Array[String],
              trip_ids: ::Array[String],
              trips_with_stop_times: ::Array[OnebusawaySDK::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping::TripsWithStopTime]
            }

            type trips_with_stop_time =
              {
                stop_times: ::Array[OnebusawaySDK::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping::TripsWithStopTime::StopTime],
                trip_id: String
              }

            class TripsWithStopTime < OnebusawaySDK::Internal::Type::BaseModel
              attr_accessor stop_times: ::Array[OnebusawaySDK::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping::TripsWithStopTime::StopTime]

              attr_accessor trip_id: String

              def initialize: (
                stop_times: ::Array[OnebusawaySDK::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping::TripsWithStopTime::StopTime],
                trip_id: String
              ) -> void

              def to_hash: -> {
                stop_times: ::Array[OnebusawaySDK::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping::TripsWithStopTime::StopTime],
                trip_id: String
              }

              type stop_time =
                {
                  arrival_enabled: bool,
                  arrival_time: Integer,
                  departure_enabled: bool,
                  departure_time: Integer,
                  stop_id: String,
                  trip_id: String,
                  service_id: String,
                  stop_headsign: String
                }

              class StopTime < OnebusawaySDK::Internal::Type::BaseModel
                attr_accessor arrival_enabled: bool

                attr_accessor arrival_time: Integer

                attr_accessor departure_enabled: bool

                attr_accessor departure_time: Integer

                attr_accessor stop_id: String

                attr_accessor trip_id: String

                attr_reader service_id: String?

                def service_id=: (String) -> String

                attr_reader stop_headsign: String?

                def stop_headsign=: (String) -> String

                def initialize: (
                  arrival_enabled: bool,
                  arrival_time: Integer,
                  departure_enabled: bool,
                  departure_time: Integer,
                  stop_id: String,
                  trip_id: String,
                  ?service_id: String,
                  ?stop_headsign: String
                ) -> void

                def to_hash: -> {
                  arrival_enabled: bool,
                  arrival_time: Integer,
                  departure_enabled: bool,
                  departure_time: Integer,
                  stop_id: String,
                  trip_id: String,
                  service_id: String,
                  stop_headsign: String
                }
              end
            end
          end
        end
      end
    end
  end
end
