module OnebusawaySDK
  module Models
    type schedule_for_route_retrieve_params =
      { date: Date } & OnebusawaySDK::request_parameters

    class ScheduleForRouteRetrieveParams < OnebusawaySDK::BaseModel
      extend OnebusawaySDK::Type::RequestParameters::Converter
      include OnebusawaySDK::RequestParameters

      attr_reader date: Date?

      def date=: (Date) -> Date

      def initialize: (
        ?date: Date,
        ?request_options: OnebusawaySDK::request_opts
      ) -> void

      def to_hash: -> OnebusawaySDK::Models::schedule_for_route_retrieve_params
    end
  end
end
