module OnebusawaySDK
  module Models
    type schedule_for_stop_retrieve_response =
      { data: OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data }

    class ScheduleForStopRetrieveResponse < OnebusawaySDK::Models::ResponseWrapper
      def data: -> OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data

      def data=: (
        OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data _
      ) -> OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data

      def initialize: (
        data: OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data
      ) -> void

      def to_hash: -> OnebusawaySDK::Models::schedule_for_stop_retrieve_response

      type data =
        {
          entry: OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data::Entry,
          references: OnebusawaySDK::Models::References
        }

      class Data < OnebusawaySDK::Internal::Type::BaseModel
        attr_accessor entry: OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data::Entry

        attr_accessor references: OnebusawaySDK::Models::References

        def initialize: (
          entry: OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data::Entry,
          references: OnebusawaySDK::Models::References
        ) -> void

        def to_hash: -> OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::data

        type entry =
          {
            date: Integer,
            stop_id: String,
            stop_route_schedules: ::Array[OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data::Entry::StopRouteSchedule]
          }

        class Entry < OnebusawaySDK::Internal::Type::BaseModel
          attr_accessor date: Integer

          attr_accessor stop_id: String

          attr_accessor stop_route_schedules: ::Array[OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data::Entry::StopRouteSchedule]

          def initialize: (
            date: Integer,
            stop_id: String,
            stop_route_schedules: ::Array[OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data::Entry::StopRouteSchedule]
          ) -> void

          def to_hash: -> OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data::entry

          type stop_route_schedule =
            {
              route_id: String,
              stop_route_direction_schedules: ::Array[OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data::Entry::StopRouteSchedule::StopRouteDirectionSchedule]
            }

          class StopRouteSchedule < OnebusawaySDK::Internal::Type::BaseModel
            attr_accessor route_id: String

            attr_accessor stop_route_direction_schedules: ::Array[OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data::Entry::StopRouteSchedule::StopRouteDirectionSchedule]

            def initialize: (
              route_id: String,
              stop_route_direction_schedules: ::Array[OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data::Entry::StopRouteSchedule::StopRouteDirectionSchedule]
            ) -> void

            def to_hash: -> OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data::Entry::stop_route_schedule

            type stop_route_direction_schedule =
              {
                schedule_stop_times: ::Array[OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data::Entry::StopRouteSchedule::StopRouteDirectionSchedule::ScheduleStopTime],
                trip_headsign: String,
                schedule_frequencies: ::Array[OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data::Entry::StopRouteSchedule::StopRouteDirectionSchedule::ScheduleFrequency]
              }

            class StopRouteDirectionSchedule < OnebusawaySDK::Internal::Type::BaseModel
              attr_accessor schedule_stop_times: ::Array[OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data::Entry::StopRouteSchedule::StopRouteDirectionSchedule::ScheduleStopTime]

              attr_accessor trip_headsign: String

              attr_reader schedule_frequencies: ::Array[OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data::Entry::StopRouteSchedule::StopRouteDirectionSchedule::ScheduleFrequency]?

              def schedule_frequencies=: (
                ::Array[OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data::Entry::StopRouteSchedule::StopRouteDirectionSchedule::ScheduleFrequency]
              ) -> ::Array[OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data::Entry::StopRouteSchedule::StopRouteDirectionSchedule::ScheduleFrequency]

              def initialize: (
                schedule_stop_times: ::Array[OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data::Entry::StopRouteSchedule::StopRouteDirectionSchedule::ScheduleStopTime],
                trip_headsign: String,
                ?schedule_frequencies: ::Array[OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data::Entry::StopRouteSchedule::StopRouteDirectionSchedule::ScheduleFrequency]
              ) -> void

              def to_hash: -> OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data::Entry::StopRouteSchedule::stop_route_direction_schedule

              type schedule_stop_time =
                {
                  arrival_enabled: bool,
                  arrival_time: Integer,
                  departure_enabled: bool,
                  departure_time: Integer,
                  service_id: String,
                  trip_id: String,
                  stop_headsign: String
                }

              class ScheduleStopTime < OnebusawaySDK::Internal::Type::BaseModel
                attr_accessor arrival_enabled: bool

                attr_accessor arrival_time: Integer

                attr_accessor departure_enabled: bool

                attr_accessor departure_time: Integer

                attr_accessor service_id: String

                attr_accessor trip_id: String

                attr_reader stop_headsign: String?

                def stop_headsign=: (String) -> String

                def initialize: (
                  arrival_enabled: bool,
                  arrival_time: Integer,
                  departure_enabled: bool,
                  departure_time: Integer,
                  service_id: String,
                  trip_id: String,
                  ?stop_headsign: String
                ) -> void

                def to_hash: -> OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data::Entry::StopRouteSchedule::StopRouteDirectionSchedule::schedule_stop_time
              end

              type schedule_frequency =
                {
                  end_time: Integer,
                  headway: Integer,
                  service_date: Integer,
                  service_id: String,
                  start_time: Integer,
                  trip_id: String
                }

              class ScheduleFrequency < OnebusawaySDK::Internal::Type::BaseModel
                attr_accessor end_time: Integer

                attr_accessor headway: Integer

                attr_accessor service_date: Integer

                attr_accessor service_id: String

                attr_accessor start_time: Integer

                attr_accessor trip_id: String

                def initialize: (
                  end_time: Integer,
                  headway: Integer,
                  service_date: Integer,
                  service_id: String,
                  start_time: Integer,
                  trip_id: String
                ) -> void

                def to_hash: -> OnebusawaySDK::Models::ScheduleForStopRetrieveResponse::Data::Entry::StopRouteSchedule::StopRouteDirectionSchedule::schedule_frequency
              end
            end
          end
        end
      end
    end
  end
end
