module OnebusawaySDK
  module Models
    type search_for_stop_list_response =
      { data: OnebusawaySDK::Models::SearchForStopListResponse::Data }

    class SearchForStopListResponse < OnebusawaySDK::Models::ResponseWrapper
      def data: -> OnebusawaySDK::Models::SearchForStopListResponse::Data?

      def data=: (
        OnebusawaySDK::Models::SearchForStopListResponse::Data _
      ) -> OnebusawaySDK::Models::SearchForStopListResponse::Data

      def initialize: (
        ?data: OnebusawaySDK::Models::SearchForStopListResponse::Data
      ) -> void

      def to_hash: -> OnebusawaySDK::Models::search_for_stop_list_response

      type data =
        {
          limit_exceeded: bool,
          list: ::Array[OnebusawaySDK::Models::SearchForStopListResponse::Data::List],
          out_of_range: bool,
          references: OnebusawaySDK::Models::References
        }

      class Data < OnebusawaySDK::Internal::Type::BaseModel
        attr_accessor limit_exceeded: bool

        attr_accessor list: ::Array[OnebusawaySDK::Models::SearchForStopListResponse::Data::List]

        attr_accessor out_of_range: bool

        attr_accessor references: OnebusawaySDK::Models::References

        def initialize: (
          limit_exceeded: bool,
          list: ::Array[OnebusawaySDK::Models::SearchForStopListResponse::Data::List],
          out_of_range: bool,
          references: OnebusawaySDK::Models::References
        ) -> void

        def to_hash: -> OnebusawaySDK::Models::SearchForStopListResponse::data

        type list =
          {
            id: String,
            lat: Float,
            lon: Float,
            name: String,
            parent: String,
            route_ids: ::Array[String],
            static_route_ids: ::Array[String],
            code: String,
            direction: String,
            location_type: Integer,
            wheelchair_boarding: String
          }

        class List < OnebusawaySDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor lat: Float

          attr_accessor lon: Float

          attr_accessor name: String

          attr_accessor parent: String

          attr_accessor route_ids: ::Array[String]

          attr_accessor static_route_ids: ::Array[String]

          attr_reader code: String?

          def code=: (String) -> String

          attr_reader direction: String?

          def direction=: (String) -> String

          attr_reader location_type: Integer?

          def location_type=: (Integer) -> Integer

          attr_reader wheelchair_boarding: String?

          def wheelchair_boarding=: (String) -> String

          def initialize: (
            id: String,
            lat: Float,
            lon: Float,
            name: String,
            parent: String,
            route_ids: ::Array[String],
            static_route_ids: ::Array[String],
            ?code: String,
            ?direction: String,
            ?location_type: Integer,
            ?wheelchair_boarding: String
          ) -> void

          def to_hash: -> OnebusawaySDK::Models::SearchForStopListResponse::Data::list
        end
      end
    end
  end
end
