module OnebusawaySDK
  module Models
    type stops_for_agency_list_response =
      {
        limit_exceeded: bool,
        list: ::Array[OnebusawaySDK::Models::StopsForAgencyListResponse::List],
        references: OnebusawaySDK::References,
        out_of_range: bool
      }

    class StopsForAgencyListResponse < OnebusawaySDK::Models::ResponseWrapper
      def limit_exceeded: -> bool

      def limit_exceeded=: (bool _) -> bool

      def list: -> ::Array[OnebusawaySDK::Models::StopsForAgencyListResponse::List]

      def list=: (
        ::Array[OnebusawaySDK::Models::StopsForAgencyListResponse::List] _
      ) -> ::Array[OnebusawaySDK::Models::StopsForAgencyListResponse::List]

      def references: -> OnebusawaySDK::References

      def references=: (
        OnebusawaySDK::References _
      ) -> OnebusawaySDK::References

      def out_of_range: -> bool?

      def out_of_range=: (bool _) -> bool

      def initialize: (
        limit_exceeded: bool,
        list: ::Array[OnebusawaySDK::Models::StopsForAgencyListResponse::List],
        references: OnebusawaySDK::References,
        ?out_of_range: bool
      ) -> void

      def to_hash: -> {
        limit_exceeded: bool,
        list: ::Array[OnebusawaySDK::Models::StopsForAgencyListResponse::List],
        references: OnebusawaySDK::References,
        out_of_range: bool
      }

      type list =
        {
          id: String,
          lat: Float,
          location_type: Integer,
          lon: Float,
          name: String,
          parent: String,
          route_ids: ::Array[String],
          static_route_ids: ::Array[String],
          code: String,
          direction: String,
          wheelchair_boarding: String
        }

      class List < OnebusawaySDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor lat: Float

        attr_accessor location_type: Integer

        attr_accessor lon: Float

        attr_accessor name: String

        attr_accessor parent: String

        attr_accessor route_ids: ::Array[String]

        attr_accessor static_route_ids: ::Array[String]

        attr_reader code: String?

        def code=: (String) -> String

        attr_reader direction: String?

        def direction=: (String) -> String

        attr_reader wheelchair_boarding: String?

        def wheelchair_boarding=: (String) -> String

        def initialize: (
          id: String,
          lat: Float,
          location_type: Integer,
          lon: Float,
          name: String,
          parent: String,
          route_ids: ::Array[String],
          static_route_ids: ::Array[String],
          ?code: String,
          ?direction: String,
          ?wheelchair_boarding: String
        ) -> void

        def to_hash: -> {
          id: String,
          lat: Float,
          location_type: Integer,
          lon: Float,
          name: String,
          parent: String,
          route_ids: ::Array[String],
          static_route_ids: ::Array[String],
          code: String,
          direction: String,
          wheelchair_boarding: String
        }
      end
    end
  end
end
