module OnebusawaySDK
  module Models
    type stop_ids_for_agency_list_params =
      {  } & OnebusawaySDK::Internal::Type::request_parameters

    class StopIDsForAgencyListParams < OnebusawaySDK::Internal::Type::BaseModel
      extend OnebusawaySDK::Internal::Type::RequestParameters::Converter
      include OnebusawaySDK::Internal::Type::RequestParameters

      def initialize: (?request_options: OnebusawaySDK::request_opts) -> void

      def to_hash: -> OnebusawaySDK::Models::stop_ids_for_agency_list_params
    end
  end
end
