module OnebusawaySDK
  module Models
    type stop_ids_for_agency_list_response =
      { data: OnebusawaySDK::Models::StopIDsForAgencyListResponse::Data }

    class StopIDsForAgencyListResponse < OnebusawaySDK::Models::ResponseWrapper
      def data: -> OnebusawaySDK::Models::StopIDsForAgencyListResponse::Data

      def data=: (
        OnebusawaySDK::Models::StopIDsForAgencyListResponse::Data _
      ) -> OnebusawaySDK::Models::StopIDsForAgencyListResponse::Data

      def initialize: (
        data: OnebusawaySDK::Models::StopIDsForAgencyListResponse::Data
      ) -> void

      type data =
        {
          limit_exceeded: bool,
          list: ::Array[String],
          references: OnebusawaySDK::References
        }

      class Data < OnebusawaySDK::Internal::Type::BaseModel
        attr_accessor limit_exceeded: bool

        attr_accessor list: ::Array[String]

        attr_accessor references: OnebusawaySDK::References

        def initialize: (
          limit_exceeded: bool,
          list: ::Array[String],
          references: OnebusawaySDK::References
        ) -> void
      end
    end
  end
end
