module OnebusawaySDK
  module Models
    type vehicles_for_agency_list_params =
      { time: String } & OnebusawaySDK::Internal::Type::request_parameters

    class VehiclesForAgencyListParams < OnebusawaySDK::BaseModel
      extend OnebusawaySDK::Internal::Type::RequestParameters::Converter
      include OnebusawaySDK::Internal::Type::RequestParameters

      attr_reader time: String?

      def time=: (String) -> String

      def initialize: (
        ?time: String,
        ?request_options: OnebusawaySDK::request_opts
      ) -> void

      def to_hash: -> OnebusawaySDK::Models::vehicles_for_agency_list_params
    end
  end
end
