module OnebusawaySDK
  module Models
    type vehicles_for_agency_list_response =
      { data: OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data }

    class VehiclesForAgencyListResponse < OnebusawaySDK::Models::ResponseWrapper
      def data: -> OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data

      def data=: (
        OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data _
      ) -> OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data

      def initialize: (
        data: OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data
      ) -> void

      def to_hash: -> {
        data: OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data
      }

      type data =
        {
          limit_exceeded: bool,
          list: ::Array[OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data::List],
          references: OnebusawaySDK::References
        }

      class Data < OnebusawaySDK::Internal::Type::BaseModel
        attr_accessor limit_exceeded: bool

        attr_accessor list: ::Array[OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data::List]

        attr_accessor references: OnebusawaySDK::References

        def initialize: (
          limit_exceeded: bool,
          list: ::Array[OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data::List],
          references: OnebusawaySDK::References
        ) -> void

        def to_hash: -> {
          limit_exceeded: bool,
          list: ::Array[OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data::List],
          references: OnebusawaySDK::References
        }

        type list =
          {
            last_location_update_time: Integer,
            last_update_time: Integer,
            location: OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data::List::Location,
            trip_id: String,
            trip_status: OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data::List::TripStatus,
            vehicle_id: String,
            occupancy_capacity: Integer,
            occupancy_count: Integer,
            occupancy_status: String,
            phase: String,
            status: String
          }

        class List < OnebusawaySDK::Internal::Type::BaseModel
          attr_accessor last_location_update_time: Integer

          attr_accessor last_update_time: Integer

          attr_accessor location: OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data::List::Location

          attr_accessor trip_id: String

          attr_accessor trip_status: OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data::List::TripStatus

          attr_accessor vehicle_id: String

          attr_reader occupancy_capacity: Integer?

          def occupancy_capacity=: (Integer) -> Integer

          attr_reader occupancy_count: Integer?

          def occupancy_count=: (Integer) -> Integer

          attr_reader occupancy_status: String?

          def occupancy_status=: (String) -> String

          attr_reader phase: String?

          def phase=: (String) -> String

          attr_reader status: String?

          def status=: (String) -> String

          def initialize: (
            last_location_update_time: Integer,
            last_update_time: Integer,
            location: OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data::List::Location,
            trip_id: String,
            trip_status: OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data::List::TripStatus,
            vehicle_id: String,
            ?occupancy_capacity: Integer,
            ?occupancy_count: Integer,
            ?occupancy_status: String,
            ?phase: String,
            ?status: String
          ) -> void

          def to_hash: -> {
            last_location_update_time: Integer,
            last_update_time: Integer,
            location: OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data::List::Location,
            trip_id: String,
            trip_status: OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data::List::TripStatus,
            vehicle_id: String,
            occupancy_capacity: Integer,
            occupancy_count: Integer,
            occupancy_status: String,
            phase: String,
            status: String
          }

          type location = { lat: Float, lon: Float }

          class Location < OnebusawaySDK::Internal::Type::BaseModel
            attr_reader lat: Float?

            def lat=: (Float) -> Float

            attr_reader lon: Float?

            def lon=: (Float) -> Float

            def initialize: (?lat: Float, ?lon: Float) -> void

            def to_hash: -> { lat: Float, lon: Float }
          end

          type trip_status =
            {
              active_trip_id: String,
              block_trip_sequence: Integer,
              closest_stop: String,
              distance_along_trip: Float,
              last_known_distance_along_trip: Float,
              last_location_update_time: Integer,
              last_update_time: Integer,
              occupancy_capacity: Integer,
              occupancy_count: Integer,
              occupancy_status: String,
              phase: String,
              predicted: bool,
              schedule_deviation: Integer,
              service_date: Integer,
              status: String,
              total_distance_along_trip: Float,
              closest_stop_time_offset: Integer,
              frequency: String,
              last_known_location: OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data::List::TripStatus::LastKnownLocation,
              last_known_orientation: Float,
              next_stop: String,
              next_stop_time_offset: Integer,
              orientation: Float,
              position: OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data::List::TripStatus::Position,
              scheduled_distance_along_trip: Float,
              situation_ids: ::Array[String],
              vehicle_id: String
            }

          class TripStatus < OnebusawaySDK::Internal::Type::BaseModel
            attr_accessor active_trip_id: String

            attr_accessor block_trip_sequence: Integer

            attr_accessor closest_stop: String

            attr_accessor distance_along_trip: Float

            attr_accessor last_known_distance_along_trip: Float

            attr_accessor last_location_update_time: Integer

            attr_accessor last_update_time: Integer

            attr_accessor occupancy_capacity: Integer

            attr_accessor occupancy_count: Integer

            attr_accessor occupancy_status: String

            attr_accessor phase: String

            attr_accessor predicted: bool

            attr_accessor schedule_deviation: Integer

            attr_accessor service_date: Integer

            attr_accessor status: String

            attr_accessor total_distance_along_trip: Float

            attr_reader closest_stop_time_offset: Integer?

            def closest_stop_time_offset=: (Integer) -> Integer

            attr_reader frequency: String?

            def frequency=: (String) -> String

            attr_reader last_known_location: OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data::List::TripStatus::LastKnownLocation?

            def last_known_location=: (
              OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data::List::TripStatus::LastKnownLocation
            ) -> OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data::List::TripStatus::LastKnownLocation

            attr_reader last_known_orientation: Float?

            def last_known_orientation=: (Float) -> Float

            attr_reader next_stop: String?

            def next_stop=: (String) -> String

            attr_reader next_stop_time_offset: Integer?

            def next_stop_time_offset=: (Integer) -> Integer

            attr_reader orientation: Float?

            def orientation=: (Float) -> Float

            attr_reader position: OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data::List::TripStatus::Position?

            def position=: (
              OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data::List::TripStatus::Position
            ) -> OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data::List::TripStatus::Position

            attr_reader scheduled_distance_along_trip: Float?

            def scheduled_distance_along_trip=: (Float) -> Float

            attr_reader situation_ids: ::Array[String]?

            def situation_ids=: (::Array[String]) -> ::Array[String]

            attr_reader vehicle_id: String?

            def vehicle_id=: (String) -> String

            def initialize: (
              active_trip_id: String,
              block_trip_sequence: Integer,
              closest_stop: String,
              distance_along_trip: Float,
              last_known_distance_along_trip: Float,
              last_location_update_time: Integer,
              last_update_time: Integer,
              occupancy_capacity: Integer,
              occupancy_count: Integer,
              occupancy_status: String,
              phase: String,
              predicted: bool,
              schedule_deviation: Integer,
              service_date: Integer,
              status: String,
              total_distance_along_trip: Float,
              ?closest_stop_time_offset: Integer,
              ?frequency: String,
              ?last_known_location: OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data::List::TripStatus::LastKnownLocation,
              ?last_known_orientation: Float,
              ?next_stop: String,
              ?next_stop_time_offset: Integer,
              ?orientation: Float,
              ?position: OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data::List::TripStatus::Position,
              ?scheduled_distance_along_trip: Float,
              ?situation_ids: ::Array[String],
              ?vehicle_id: String
            ) -> void

            def to_hash: -> {
              active_trip_id: String,
              block_trip_sequence: Integer,
              closest_stop: String,
              distance_along_trip: Float,
              last_known_distance_along_trip: Float,
              last_location_update_time: Integer,
              last_update_time: Integer,
              occupancy_capacity: Integer,
              occupancy_count: Integer,
              occupancy_status: String,
              phase: String,
              predicted: bool,
              schedule_deviation: Integer,
              service_date: Integer,
              status: String,
              total_distance_along_trip: Float,
              closest_stop_time_offset: Integer,
              frequency: String,
              last_known_location: OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data::List::TripStatus::LastKnownLocation,
              last_known_orientation: Float,
              next_stop: String,
              next_stop_time_offset: Integer,
              orientation: Float,
              position: OnebusawaySDK::Models::VehiclesForAgencyListResponse::Data::List::TripStatus::Position,
              scheduled_distance_along_trip: Float,
              situation_ids: ::Array[String],
              vehicle_id: String
            }

            type last_known_location = { lat: Float, lon: Float }

            class LastKnownLocation < OnebusawaySDK::Internal::Type::BaseModel
              attr_reader lat: Float?

              def lat=: (Float) -> Float

              attr_reader lon: Float?

              def lon=: (Float) -> Float

              def initialize: (?lat: Float, ?lon: Float) -> void

              def to_hash: -> { lat: Float, lon: Float }
            end

            type position = { lat: Float, lon: Float }

            class Position < OnebusawaySDK::Internal::Type::BaseModel
              attr_reader lat: Float?

              def lat=: (Float) -> Float

              attr_reader lon: Float?

              def lon=: (Float) -> Float

              def initialize: (?lat: Float, ?lon: Float) -> void

              def to_hash: -> { lat: Float, lon: Float }
            end
          end
        end
      end
    end
  end
end
