module Onebusaway
  class Error < StandardError
    attr_reader cause: StandardError?
  end

  class ConversionError < Onebusaway::Error
  end

  class APIError < Onebusaway::Error
    attr_reader url: URI::Generic

    attr_reader status: Integer?

    attr_reader body: top?

    def initialize: (
      url: URI::Generic,
      status: Integer?,
      body: Object?,
      request: nil,
      response: nil,
      message: String?
    ) -> void
  end

  class APIConnectionError < Onebusaway::APIError
    def initialize: (
      url: URI::Generic,
      status: nil,
      body: nil,
      request: nil,
      response: nil,
      message: String?
    ) -> void
  end

  class APITimeoutError < Onebusaway::APIConnectionError
    def initialize: (
      url: URI::Generic,
      status: nil,
      body: nil,
      request: nil,
      response: nil,
      message: String?
    ) -> void
  end

  class APIStatusError < Onebusaway::APIError
    def self.for: (
      url: URI::Generic,
      status: Integer,
      body: Object?,
      request: nil,
      response: nil
    ) -> instance

    def initialize: (
      url: URI::Generic,
      status: Integer,
      body: Object?,
      request: nil,
      response: nil,
      message: String?
    ) -> void
  end

  class BadRequestError < Onebusaway::APIStatusError
    HTTP_STATUS: 400
  end

  class AuthenticationError < Onebusaway::APIStatusError
    HTTP_STATUS: 401
  end

  class PermissionDeniedError < Onebusaway::APIStatusError
    HTTP_STATUS: 403
  end

  class NotFoundError < Onebusaway::APIStatusError
    HTTP_STATUS: 404
  end

  class ConflictError < Onebusaway::APIStatusError
    HTTP_STATUS: 409
  end

  class UnprocessableEntityError < Onebusaway::APIStatusError
    HTTP_STATUS: 422
  end

  class RateLimitError < Onebusaway::APIStatusError
    HTTP_STATUS: 429
  end

  class InternalServerError < Onebusaway::APIStatusError
    HTTP_STATUS: Range[Integer]
  end
end
