module OpenTransit
  module Resources
    class Agency
      def retrieve: (
        String agency_id,
        ?request_options: OpenTransit::request_opts
      ) -> OpenTransit::Models::AgencyRetrieveResponse

      def initialize: (client: OpenTransit::Client) -> void
    end
  end
end
