module OpenTransit
  module Resources
    class Block
      def retrieve: (
        String block_id,
        ?request_options: OpenTransit::request_opts
      ) -> OpenTransit::Models::BlockRetrieveResponse

      def initialize: (client: OpenTransit::Client) -> void
    end
  end
end
