module OpenTransit
  module Resources
    class RouteIDsForAgency
      def list: (
        String agency_id,
        ?request_options: OpenTransit::request_opts
      ) -> OpenTransit::Models::RouteIDsForAgencyListResponse

      def initialize: (client: OpenTransit::Client) -> void
    end
  end
end
