module OpenTransit
  module Resources
    class StopsForAgency
      def list: (
        String agency_id,
        ?request_options: OpenTransit::request_opts
      ) -> OpenTransit::Models::StopsForAgencyListResponse

      def initialize: (client: OpenTransit::Client) -> void
    end
  end
end
