module OpenTransit
  module Resources
    class StopsForRoute
      def list: (
        String route_id,
        ?include_polylines: bool,
        ?time: String,
        ?request_options: OpenTransit::request_opts
      ) -> OpenTransit::Models::StopsForRouteListResponse

      def initialize: (client: OpenTransit::Client) -> void
    end
  end
end
