module OpenTransit
  module Resources
    class CurrentTime
      def retrieve:
        (
          ?OpenTransit::Models::CurrentTimeRetrieveParams
          | Hash[Symbol, top] params
        ) -> OpenTransit::Models::CurrentTimeRetrieveResponse
        | (
          request_options: OpenTransit::request_opts
        ) -> OpenTransit::Models::CurrentTimeRetrieveResponse

      def initialize: (client: OpenTransit::Client) -> void
    end
  end
end
