module OpenTransit
  module Resources
    class ReportProblemWithTrip
      def retrieve:
        (
          String trip_id,
          ?OpenTransit::Models::ReportProblemWithTripRetrieveParams
          | Hash[Symbol, top] params
        ) -> OpenTransit::Models::ResponseWrapper
        | (
          String trip_id,
          code: OpenTransit::Models::ReportProblemWithTripRetrieveParams::code,
          service_date: Integer,
          stop_id: String,
          user_comment: String,
          user_lat: Float,
          user_location_accuracy: Float,
          user_lon: Float,
          user_on_vehicle: bool,
          user_vehicle_number: String,
          vehicle_id: String,
          request_options: OpenTransit::request_opts
        ) -> OpenTransit::Models::ResponseWrapper

      def initialize: (client: OpenTransit::Client) -> void
    end
  end
end
