module OpenTransit
  module Resources
    class Route
      def retrieve:
        (
          String route_id,
          ?OpenTransit::Models::RouteRetrieveParams | Hash[Symbol, top] params
        ) -> OpenTransit::Models::RouteRetrieveResponse
        | (
          String route_id,
          request_options: OpenTransit::request_opts
        ) -> OpenTransit::Models::RouteRetrieveResponse

      def initialize: (client: OpenTransit::Client) -> void
    end
  end
end
