module OpenTransit
  module Resources
    class RoutesForLocation
      def list:
        (
          OpenTransit::Models::RoutesForLocationListParams
          | Hash[Symbol, top] params
        ) -> OpenTransit::Models::RoutesForLocationListResponse
        | (
          lat: Float,
          lon: Float,
          lat_span: Float,
          lon_span: Float,
          query: String,
          radius: Float,
          request_options: OpenTransit::request_opts
        ) -> OpenTransit::Models::RoutesForLocationListResponse

      def initialize: (client: OpenTransit::Client) -> void
    end
  end
end
