module OpenTransit
  module Resources
    class ScheduleForStop
      def retrieve:
        (
          String stop_id,
          ?OpenTransit::Models::ScheduleForStopRetrieveParams
          | Hash[Symbol, top] params
        ) -> OpenTransit::Models::ScheduleForStopRetrieveResponse
        | (
          String stop_id,
          date: Date,
          request_options: OpenTransit::request_opts
        ) -> OpenTransit::Models::ScheduleForStopRetrieveResponse

      def initialize: (client: OpenTransit::Client) -> void
    end
  end
end
