module OpenTransit
  module Resources
    class Stop
      def retrieve:
        (
          String stop_id,
          ?OpenTransit::Models::StopRetrieveParams | Hash[Symbol, top] params
        ) -> OpenTransit::Models::StopRetrieveResponse
        | (
          String stop_id,
          request_options: OpenTransit::request_opts
        ) -> OpenTransit::Models::StopRetrieveResponse

      def initialize: (client: OpenTransit::Client) -> void
    end
  end
end
