module OpenTransit
  module Resources
    class StopIDsForAgency
      def list:
        (
          String agency_id,
          ?OpenTransit::Models::StopIDsForAgencyListParams
          | Hash[Symbol, top] params
        ) -> OpenTransit::Models::StopIDsForAgencyListResponse
        | (
          String agency_id,
          request_options: OpenTransit::request_opts
        ) -> OpenTransit::Models::StopIDsForAgencyListResponse

      def initialize: (client: OpenTransit::Client) -> void
    end
  end
end
