module OpenTransit
  module Resources
    class VehiclesForAgency
      def list:
        (
          String agency_id,
          ?OpenTransit::Models::VehiclesForAgencyListParams
          | Hash[Symbol, top] params
        ) -> OpenTransit::Models::VehiclesForAgencyListResponse
        | (
          String agency_id,
          time: String,
          request_options: OpenTransit::request_opts
        ) -> OpenTransit::Models::VehiclesForAgencyListResponse

      def initialize: (client: OpenTransit::Client) -> void
    end
  end
end
