module OpenTransit
  module Models
    type arrival_and_departure_list_params =
      { minutes_after: Integer, minutes_before: Integer, time: Time }
      & OpenTransit::Internal::Type::request_parameters

    class ArrivalAndDepartureListParams < OpenTransit::Internal::Type::BaseModel
      extend OpenTransit::Internal::Type::RequestParameters::Converter
      include OpenTransit::Internal::Type::RequestParameters

      attr_reader minutes_after: Integer?

      def minutes_after=: (Integer) -> Integer

      attr_reader minutes_before: Integer?

      def minutes_before=: (Integer) -> Integer

      attr_reader time: Time?

      def time=: (Time) -> Time

      def initialize: (
        ?minutes_after: Integer,
        ?minutes_before: Integer,
        ?time: Time,
        ?request_options: OpenTransit::request_opts
      ) -> void
    end
  end
end
