module OpenTransit
  module Models
    type routes_for_location_list_params =
      {
        lat: Float,
        lon: Float,
        lat_span: Float,
        lon_span: Float,
        query: String,
        radius: Float
      }
      & OpenTransit::Internal::Type::request_parameters

    class RoutesForLocationListParams < OpenTransit::Internal::Type::BaseModel
      extend OpenTransit::Internal::Type::RequestParameters::Converter
      include OpenTransit::Internal::Type::RequestParameters

      attr_accessor lat: Float

      attr_accessor lon: Float

      attr_reader lat_span: Float?

      def lat_span=: (Float) -> Float

      attr_reader lon_span: Float?

      def lon_span=: (Float) -> Float

      attr_reader query: String?

      def query=: (String) -> String

      attr_reader radius: Float?

      def radius=: (Float) -> Float

      def initialize: (
        lat: Float,
        lon: Float,
        ?lat_span: Float,
        ?lon_span: Float,
        ?query: String,
        ?radius: Float,
        ?request_options: OpenTransit::request_opts
      ) -> void
    end
  end
end
