module OpenTransit
  module Models
    type schedule_for_route_retrieve_response =
      { data: OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data }

    class ScheduleForRouteRetrieveResponse < OpenTransit::Models::ResponseWrapper
      def data: -> OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data

      def data=: (
        OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data _
      ) -> OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data

      def initialize: (
        data: OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data
      ) -> void

      type data =
        {
          entry: OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data::Entry
        }

      class Data < OpenTransit::Internal::Type::BaseModel
        attr_accessor entry: OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data::Entry

        def initialize: (
          entry: OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data::Entry
        ) -> void

        type entry =
          {
            route_id: String,
            schedule_date: Integer,
            service_ids: ::Array[String],
            stops: ::Array[OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data::Entry::Stop],
            stop_trip_groupings: ::Array[OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping],
            trips: ::Array[OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data::Entry::Trip]
          }

        class Entry < OpenTransit::Internal::Type::BaseModel
          attr_accessor route_id: String

          attr_accessor schedule_date: Integer

          attr_accessor service_ids: ::Array[String]

          attr_accessor stops: ::Array[OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data::Entry::Stop]

          attr_accessor stop_trip_groupings: ::Array[OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping]

          attr_accessor trips: ::Array[OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data::Entry::Trip]

          def initialize: (
            route_id: String,
            schedule_date: Integer,
            service_ids: ::Array[String],
            stops: ::Array[OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data::Entry::Stop],
            stop_trip_groupings: ::Array[OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping],
            trips: ::Array[OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data::Entry::Trip]
          ) -> void

          type stop =
            {
              id: String,
              lat: Float,
              location_type: Integer,
              lon: Float,
              name: String,
              parent: String,
              route_ids: ::Array[String],
              static_route_ids: ::Array[String],
              code: String,
              direction: String,
              wheelchair_boarding: String
            }

          class Stop < OpenTransit::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor lat: Float

            attr_accessor location_type: Integer

            attr_accessor lon: Float

            attr_accessor name: String

            attr_accessor parent: String

            attr_accessor route_ids: ::Array[String]

            attr_accessor static_route_ids: ::Array[String]

            attr_reader code: String?

            def code=: (String) -> String

            attr_reader direction: String?

            def direction=: (String) -> String

            attr_reader wheelchair_boarding: String?

            def wheelchair_boarding=: (String) -> String

            def initialize: (
              id: String,
              lat: Float,
              location_type: Integer,
              lon: Float,
              name: String,
              parent: String,
              route_ids: ::Array[String],
              static_route_ids: ::Array[String],
              ?code: String,
              ?direction: String,
              ?wheelchair_boarding: String
            ) -> void
          end

          type stop_trip_grouping =
            {
              direction_id: String,
              stop_ids: ::Array[String],
              trip_headsigns: ::Array[String],
              trip_ids: ::Array[String],
              trips_with_stop_times: ::Array[OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping::TripsWithStopTime]
            }

          class StopTripGrouping < OpenTransit::Internal::Type::BaseModel
            attr_accessor direction_id: String

            attr_accessor stop_ids: ::Array[String]

            attr_accessor trip_headsigns: ::Array[String]

            attr_accessor trip_ids: ::Array[String]

            attr_reader trips_with_stop_times: ::Array[OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping::TripsWithStopTime]?

            def trips_with_stop_times=: (
              ::Array[OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping::TripsWithStopTime]
            ) -> ::Array[OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping::TripsWithStopTime]

            def initialize: (
              direction_id: String,
              stop_ids: ::Array[String],
              trip_headsigns: ::Array[String],
              trip_ids: ::Array[String],
              ?trips_with_stop_times: ::Array[OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping::TripsWithStopTime]
            ) -> void

            type trips_with_stop_time =
              {
                stop_times: ::Array[OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping::TripsWithStopTime::StopTime],
                trip_id: String
              }

            class TripsWithStopTime < OpenTransit::Internal::Type::BaseModel
              attr_accessor stop_times: ::Array[OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping::TripsWithStopTime::StopTime]

              attr_accessor trip_id: String

              def initialize: (
                stop_times: ::Array[OpenTransit::Models::ScheduleForRouteRetrieveResponse::Data::Entry::StopTripGrouping::TripsWithStopTime::StopTime],
                trip_id: String
              ) -> void

              type stop_time =
                {
                  arrival_enabled: bool,
                  arrival_time: Integer,
                  departure_enabled: bool,
                  departure_time: Integer,
                  stop_id: String,
                  trip_id: String,
                  service_id: String,
                  stop_headsign: String
                }

              class StopTime < OpenTransit::Internal::Type::BaseModel
                attr_accessor arrival_enabled: bool

                attr_accessor arrival_time: Integer

                attr_accessor departure_enabled: bool

                attr_accessor departure_time: Integer

                attr_accessor stop_id: String

                attr_accessor trip_id: String

                attr_reader service_id: String?

                def service_id=: (String) -> String

                attr_reader stop_headsign: String?

                def stop_headsign=: (String) -> String

                def initialize: (
                  arrival_enabled: bool,
                  arrival_time: Integer,
                  departure_enabled: bool,
                  departure_time: Integer,
                  stop_id: String,
                  trip_id: String,
                  ?service_id: String,
                  ?stop_headsign: String
                ) -> void
              end
            end
          end

          type trip =
            {
              id: String,
              route_id: String,
              service_id: String,
              block_id: String,
              direction_id: String,
              peak_offpeak: Integer,
              route_short_name: String,
              shape_id: String,
              time_zone: String,
              trip_headsign: String,
              trip_short_name: String
            }

          class Trip < OpenTransit::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor route_id: String

            attr_accessor service_id: String

            attr_reader block_id: String?

            def block_id=: (String) -> String

            attr_reader direction_id: String?

            def direction_id=: (String) -> String

            attr_reader peak_offpeak: Integer?

            def peak_offpeak=: (Integer) -> Integer

            attr_reader route_short_name: String?

            def route_short_name=: (String) -> String

            attr_reader shape_id: String?

            def shape_id=: (String) -> String

            attr_reader time_zone: String?

            def time_zone=: (String) -> String

            attr_reader trip_headsign: String?

            def trip_headsign=: (String) -> String

            attr_reader trip_short_name: String?

            def trip_short_name=: (String) -> String

            def initialize: (
              id: String,
              route_id: String,
              service_id: String,
              ?block_id: String,
              ?direction_id: String,
              ?peak_offpeak: Integer,
              ?route_short_name: String,
              ?shape_id: String,
              ?time_zone: String,
              ?trip_headsign: String,
              ?trip_short_name: String
            ) -> void
          end
        end
      end
    end
  end
end
