module OpenTransit
  module Models
    type shape_retrieve_response =
      { data: OpenTransit::Models::ShapeRetrieveResponse::Data }

    class ShapeRetrieveResponse < OpenTransit::Models::ResponseWrapper
      def data: -> OpenTransit::Models::ShapeRetrieveResponse::Data

      def data=: (
        OpenTransit::Models::ShapeRetrieveResponse::Data _
      ) -> OpenTransit::Models::ShapeRetrieveResponse::Data

      def initialize: (
        data: OpenTransit::Models::ShapeRetrieveResponse::Data
      ) -> void

      type data =
        {
          entry: OpenTransit::Models::ShapeRetrieveResponse::Data::Entry,
          references: OpenTransit::References
        }

      class Data < OpenTransit::Internal::Type::BaseModel
        attr_accessor entry: OpenTransit::Models::ShapeRetrieveResponse::Data::Entry

        attr_accessor references: OpenTransit::References

        def initialize: (
          entry: OpenTransit::Models::ShapeRetrieveResponse::Data::Entry,
          references: OpenTransit::References
        ) -> void

        type entry = { length: Integer, points: String, levels: String }

        class Entry < OpenTransit::Internal::Type::BaseModel
          attr_accessor length: Integer

          attr_accessor points: String

          attr_reader levels: String?

          def levels=: (String) -> String

          def initialize: (
            length: Integer,
            points: String,
            ?levels: String
          ) -> void
        end
      end
    end
  end
end
