module OpenTransit
  module Models
    type stops_for_location_list_response =
      { data: OpenTransit::Models::StopsForLocationListResponse::Data }

    class StopsForLocationListResponse < OpenTransit::Models::ResponseWrapper
      def data: -> OpenTransit::Models::StopsForLocationListResponse::Data

      def data=: (
        OpenTransit::Models::StopsForLocationListResponse::Data _
      ) -> OpenTransit::Models::StopsForLocationListResponse::Data

      def initialize: (
        data: OpenTransit::Models::StopsForLocationListResponse::Data
      ) -> void

      type data =
        {
          limit_exceeded: bool,
          list: ::Array[OpenTransit::Models::StopsForLocationListResponse::Data::List],
          references: OpenTransit::References,
          out_of_range: bool
        }

      class Data < OpenTransit::Internal::Type::BaseModel
        attr_accessor limit_exceeded: bool

        attr_accessor list: ::Array[OpenTransit::Models::StopsForLocationListResponse::Data::List]

        attr_accessor references: OpenTransit::References

        attr_reader out_of_range: bool?

        def out_of_range=: (bool) -> bool

        def initialize: (
          limit_exceeded: bool,
          list: ::Array[OpenTransit::Models::StopsForLocationListResponse::Data::List],
          references: OpenTransit::References,
          ?out_of_range: bool
        ) -> void

        type list =
          {
            id: String,
            lat: Float,
            location_type: Integer,
            lon: Float,
            name: String,
            parent: String,
            route_ids: ::Array[String],
            static_route_ids: ::Array[String],
            code: String,
            direction: String,
            wheelchair_boarding: String
          }

        class List < OpenTransit::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor lat: Float

          attr_accessor location_type: Integer

          attr_accessor lon: Float

          attr_accessor name: String

          attr_accessor parent: String

          attr_accessor route_ids: ::Array[String]

          attr_accessor static_route_ids: ::Array[String]

          attr_reader code: String?

          def code=: (String) -> String

          attr_reader direction: String?

          def direction=: (String) -> String

          attr_reader wheelchair_boarding: String?

          def wheelchair_boarding=: (String) -> String

          def initialize: (
            id: String,
            lat: Float,
            location_type: Integer,
            lon: Float,
            name: String,
            parent: String,
            route_ids: ::Array[String],
            static_route_ids: ::Array[String],
            ?code: String,
            ?direction: String,
            ?wheelchair_boarding: String
          ) -> void
        end
      end
    end
  end
end
