module OpenTransit
  module Models
    type trip_for_vehicle_retrieve_params =
      {
        include_schedule: bool,
        include_status: bool,
        include_trip: bool,
        time: Integer
      }
      & OpenTransit::Internal::Type::request_parameters

    class TripForVehicleRetrieveParams < OpenTransit::Internal::Type::BaseModel
      extend OpenTransit::Internal::Type::RequestParameters::Converter
      include OpenTransit::Internal::Type::RequestParameters

      attr_reader include_schedule: bool?

      def include_schedule=: (bool) -> bool

      attr_reader include_status: bool?

      def include_status=: (bool) -> bool

      attr_reader include_trip: bool?

      def include_trip=: (bool) -> bool

      attr_reader time: Integer?

      def time=: (Integer) -> Integer

      def initialize: (
        ?include_schedule: bool,
        ?include_status: bool,
        ?include_trip: bool,
        ?time: Integer,
        ?request_options: OpenTransit::request_opts
      ) -> void
    end
  end
end
