module OnebusawaySDK
  module Resources
    class SearchForStop
      def list: (
        input: String,
        ?max_count: Integer,
        ?request_options: OnebusawaySDK::request_opts
      ) -> OnebusawaySDK::Models::SearchForStopListResponse

      def initialize: (client: OnebusawaySDK::Client) -> void
    end
  end
end
