module OnebusawaySDK
  module Resources
    class StopIDsForAgency
      def list: (
        String agency_id,
        ?request_options: OnebusawaySDK::request_opts
      ) -> OnebusawaySDK::Models::StopIDsForAgencyListResponse

      def initialize: (client: OnebusawaySDK::Client) -> void
    end
  end
end
