module OnebusawaySDK
  class Unknown = OnebusawaySDK::Internal::Type::Unknown

  class BooleanModel = OnebusawaySDK::Internal::Type::BooleanModel

  module Enum = OnebusawaySDK::Internal::Type::Enum

  module Union = OnebusawaySDK::Internal::Type::Union

  class ArrayOf = OnebusawaySDK::Internal::Type::ArrayOf

  class HashOf = OnebusawaySDK::Internal::Type::HashOf

  class BaseModel = OnebusawaySDK::Internal::Type::BaseModel

  type request_parameters = OnebusawaySDK::Internal::Type::request_parameters

  module RequestParameters = OnebusawaySDK::Internal::Type::RequestParameters
end
