module OnebusawaySDK
  module Internal
    extend OnebusawaySDK::Internal::Util::SorbetRuntimeSupport

    type file_input =
      Pathname | StringIO | IO | String | OnebusawaySDK::FilePart

    OMIT: Object
  end
end
