module OnebusawaySDK
  module Resources
    class Config
      def retrieve: (
        ?request_options: OnebusawaySDK::request_opts
      ) -> OnebusawaySDK::Models::ConfigRetrieveResponse

      def initialize: (client: OnebusawaySDK::Client) -> void
    end
  end
end
