module OnebusawaySDK
  module Resources
    class CurrentTime
      def retrieve: (
        ?request_options: OnebusawaySDK::request_opts
      ) -> OnebusawaySDK::Models::CurrentTimeRetrieveResponse

      def initialize: (client: OnebusawaySDK::Client) -> void
    end
  end
end
