module OnebusawaySDK
  module Resources
    class ReportProblemWithStop
      def retrieve:
        (
          String stop_id,
          ?OnebusawaySDK::Models::ReportProblemWithStopRetrieveParams
          | ::Hash[Symbol, top] params
        ) -> OnebusawaySDK::Models::ResponseWrapper
        | (
          String stop_id,
          code: OnebusawaySDK::Models::ReportProblemWithStopRetrieveParams::code,
          user_comment: String,
          user_lat: Float,
          user_location_accuracy: Float,
          user_lon: Float,
          request_options: OnebusawaySDK::request_opts
        ) -> OnebusawaySDK::Models::ResponseWrapper

      def initialize: (client: OnebusawaySDK::Client) -> void
    end
  end
end
