module OnebusawaySDK
  module Resources
    class RoutesForLocation
      def list: (
        lat: Float,
        lon: Float,
        ?lat_span: Float,
        ?lon_span: Float,
        ?query: String,
        ?radius: Float,
        ?request_options: OnebusawaySDK::request_opts
      ) -> OnebusawaySDK::Models::RoutesForLocationListResponse

      def initialize: (client: OnebusawaySDK::Client) -> void
    end
  end
end
