module OnebusawaySDK
  module Resources
    class SearchForStop
      def list:
        (
          OnebusawaySDK::Models::SearchForStopListParams
          | ::Hash[Symbol, top] params
        ) -> OnebusawaySDK::Models::SearchForStopListResponse
        | (
          input: String,
          ?max_count: Integer,
          ?request_options: OnebusawaySDK::request_opts
        ) -> OnebusawaySDK::Models::SearchForStopListResponse

      def initialize: (client: OnebusawaySDK::Client) -> void
    end
  end
end
