module OnebusawaySDK
  module Resources
    class StopsForLocation
      def list:
        (
          OnebusawaySDK::Models::StopsForLocationListParams
          | ::Hash[Symbol, top] params
        ) -> OnebusawaySDK::Models::StopsForLocationListResponse
        | (
          lat: Float,
          lon: Float,
          lat_span: Float,
          lon_span: Float,
          query: String,
          radius: Float,
          request_options: OnebusawaySDK::request_opts
        ) -> OnebusawaySDK::Models::StopsForLocationListResponse

      def initialize: (client: OnebusawaySDK::Client) -> void
    end
  end
end
