module OnebusawaySDK
  module Resources
    class TripDetails
      def retrieve:
        (
          String trip_id,
          ?OnebusawaySDK::Models::TripDetailRetrieveParams
          | ::Hash[Symbol, top] params
        ) -> OnebusawaySDK::Models::TripDetailRetrieveResponse
        | (
          String trip_id,
          ?include_schedule: bool,
          ?include_status: bool,
          ?include_trip: bool,
          ?service_date: Integer,
          ?time: Integer,
          ?request_options: OnebusawaySDK::request_opts
        ) -> OnebusawaySDK::Models::TripDetailRetrieveResponse

      def initialize: (client: OnebusawaySDK::Client) -> void
    end
  end
end
