module OnebusawaySDK
  module Resources
    class Trip
      def retrieve: (
        String trip_id,
        ?request_options: OnebusawaySDK::request_opts
      ) -> OnebusawaySDK::Models::TripRetrieveResponse

      def initialize: (client: OnebusawaySDK::Client) -> void
    end
  end
end
