module OnebusawaySDK
  module Resources
    class TripsForRoute
      def list: (
        String route_id,
        ?include_schedule: bool,
        ?include_status: bool,
        ?time: Integer,
        ?request_options: OnebusawaySDK::request_opts
      ) -> OnebusawaySDK::Models::TripsForRouteListResponse

      def initialize: (client: OnebusawaySDK::Client) -> void
    end
  end
end
