module Onebusaway
  module Resources
    class AgenciesWithCoverage
      def list:
        (
          ?Onebusaway::Models::AgenciesWithCoverageListParams
          | ::Hash[Symbol, top] params
        ) -> Onebusaway::Models::AgenciesWithCoverageListResponse
        | (
          request_options: Onebusaway::request_opts
        ) -> Onebusaway::Models::AgenciesWithCoverageListResponse

      def initialize: (client: Onebusaway::Client) -> void
    end
  end
end
