module Onebusaway
  module Resources
    class ArrivalAndDeparture
      def retrieve:
        (
          String stop_id,
          Onebusaway::Models::ArrivalAndDepartureRetrieveParams
          | ::Hash[Symbol, top] params
        ) -> Onebusaway::Models::ArrivalAndDepartureRetrieveResponse
        | (
          String stop_id,
          service_date: Integer,
          trip_id: String,
          stop_sequence: Integer,
          time: Integer,
          vehicle_id: String,
          request_options: Onebusaway::request_opts
        ) -> Onebusaway::Models::ArrivalAndDepartureRetrieveResponse

      def list:
        (
          String stop_id,
          ?Onebusaway::Models::ArrivalAndDepartureListParams
          | ::Hash[Symbol, top] params
        ) -> Onebusaway::Models::ArrivalAndDepartureListResponse
        | (
          String stop_id,
          minutes_after: Integer,
          minutes_before: Integer,
          time: Time,
          request_options: Onebusaway::request_opts
        ) -> Onebusaway::Models::ArrivalAndDepartureListResponse

      def initialize: (client: Onebusaway::Client) -> void
    end
  end
end
