module Onebusaway
  module Resources
    class Config
      def retrieve:
        (
          ?Onebusaway::Models::ConfigRetrieveParams | Hash[Symbol, top] params
        ) -> Onebusaway::Models::ConfigRetrieveResponse
        | (
          request_options: Onebusaway::request_opts
        ) -> Onebusaway::Models::ConfigRetrieveResponse

      def initialize: (client: Onebusaway::Client) -> void
    end
  end
end
