module Onebusaway
  module Resources
    class ReportProblemWithStop
      def retrieve:
        (
          String stop_id,
          ?Onebusaway::Models::ReportProblemWithStopRetrieveParams
          | Hash[Symbol, top] params
        ) -> Onebusaway::Models::ResponseWrapper
        | (
          String stop_id,
          code: Onebusaway::Models::ReportProblemWithStopRetrieveParams::code,
          user_comment: String,
          user_lat: Float,
          user_location_accuracy: Float,
          user_lon: Float,
          request_options: Onebusaway::request_opts
        ) -> Onebusaway::Models::ResponseWrapper

      def initialize: (client: Onebusaway::Client) -> void
    end
  end
end
