module Onebusaway
  module Resources
    class RoutesForAgency
      def list:
        (
          String agency_id,
          ?Onebusaway::Models::RoutesForAgencyListParams
          | Hash[Symbol, top] params
        ) -> Onebusaway::Models::RoutesForAgencyListResponse
        | (
          String agency_id,
          request_options: Onebusaway::request_opts
        ) -> Onebusaway::Models::RoutesForAgencyListResponse

      def initialize: (client: Onebusaway::Client) -> void
    end
  end
end
