module Onebusaway
  module Resources
    class SearchForStop
      def list:
        (
          Onebusaway::Models::SearchForStopListParams | Hash[Symbol, top] params
        ) -> Onebusaway::Models::SearchForStopListResponse
        | (
          input: String,
          max_count: Integer,
          request_options: Onebusaway::request_opts
        ) -> Onebusaway::Models::SearchForStopListResponse

      def initialize: (client: Onebusaway::Client) -> void
    end
  end
end
