module Onebusaway
  module Resources
    class Shape
      def retrieve:
        (
          String shape_id,
          ?Onebusaway::Models::ShapeRetrieveParams | Hash[Symbol, top] params
        ) -> Onebusaway::Models::ShapeRetrieveResponse
        | (
          String shape_id,
          request_options: Onebusaway::request_opts
        ) -> Onebusaway::Models::ShapeRetrieveResponse

      def initialize: (client: Onebusaway::Client) -> void
    end
  end
end
