module Onebusaway
  module Resources
    class StopsForRoute
      def list:
        (
          String route_id,
          ?Onebusaway::Models::StopsForRouteListParams
          | ::Hash[Symbol, top] params
        ) -> Onebusaway::Models::StopsForRouteListResponse
        | (
          String route_id,
          include_polylines: bool,
          time: String,
          request_options: Onebusaway::request_opts
        ) -> Onebusaway::Models::StopsForRouteListResponse

      def initialize: (client: Onebusaway::Client) -> void
    end
  end
end
