module Onebusaway
  module Resources
    class StopsForLocation
      def list:
        (
          Onebusaway::Models::StopsForLocationListParams
          | Hash[Symbol, top] params
        ) -> Onebusaway::Models::StopsForLocationListResponse
        | (
          lat: Float,
          lon: Float,
          lat_span: Float,
          lon_span: Float,
          query: String,
          radius: Float,
          request_options: Onebusaway::request_opts
        ) -> Onebusaway::Models::StopsForLocationListResponse

      def initialize: (client: Onebusaway::Client) -> void
    end
  end
end
