module Onebusaway
  module Resources
    class TripDetails
      def retrieve:
        (
          String trip_id,
          ?Onebusaway::Models::TripDetailRetrieveParams
          | ::Hash[Symbol, top] params
        ) -> Onebusaway::Models::TripDetailRetrieveResponse
        | (
          String trip_id,
          include_schedule: bool,
          include_status: bool,
          include_trip: bool,
          service_date: Integer,
          time: Integer,
          request_options: Onebusaway::request_opts
        ) -> Onebusaway::Models::TripDetailRetrieveResponse

      def initialize: (client: Onebusaway::Client) -> void
    end
  end
end
