module Onebusaway
  module Resources
    class TripsForRoute
      def list:
        (
          String route_id,
          ?Onebusaway::Models::TripsForRouteListParams
          | ::Hash[Symbol, top] params
        ) -> Onebusaway::Models::TripsForRouteListResponse
        | (
          String route_id,
          include_schedule: bool,
          include_status: bool,
          time: Integer,
          request_options: Onebusaway::request_opts
        ) -> Onebusaway::Models::TripsForRouteListResponse

      def initialize: (client: Onebusaway::Client) -> void
    end
  end
end
