module OpenTransit
  module Models
    type agencies_with_coverage_list_response =
      { data: OpenTransit::Models::AgenciesWithCoverageListResponse::Data }

    class AgenciesWithCoverageListResponse < OpenTransit::Models::ResponseWrapper
      attr_accessor data: OpenTransit::Models::AgenciesWithCoverageListResponse::Data

      def initialize:
        (
          data: OpenTransit::Models::AgenciesWithCoverageListResponse::Data
        ) -> void
        | (
          ?OpenTransit::Models::agencies_with_coverage_list_response
          | OpenTransit::BaseModel data
        ) -> void

      def to_hash: -> OpenTransit::Models::agencies_with_coverage_list_response

      type data =
        {
          limit_exceeded: bool,
          list: Array[OpenTransit::Models::AgenciesWithCoverageListResponse::Data::List],
          references: OpenTransit::Models::References
        }

      class Data < OpenTransit::BaseModel
        attr_accessor limit_exceeded: bool

        attr_accessor list: Array[OpenTransit::Models::AgenciesWithCoverageListResponse::Data::List]

        attr_accessor references: OpenTransit::Models::References

        def initialize:
          (
            limit_exceeded: bool,
            list: Array[OpenTransit::Models::AgenciesWithCoverageListResponse::Data::List],
            references: OpenTransit::Models::References
          ) -> void
          | (
            ?OpenTransit::Models::AgenciesWithCoverageListResponse::data
            | OpenTransit::BaseModel data
          ) -> void

        def to_hash: -> OpenTransit::Models::AgenciesWithCoverageListResponse::data

        type list =
          {
            agency_id: String,
            lat: Float,
            lat_span: Float,
            lon: Float,
            lon_span: Float
          }

        class List < OpenTransit::BaseModel
          attr_accessor agency_id: String

          attr_accessor lat: Float

          attr_accessor lat_span: Float

          attr_accessor lon: Float

          attr_accessor lon_span: Float

          def initialize:
            (
              agency_id: String,
              lat: Float,
              lat_span: Float,
              lon: Float,
              lon_span: Float
            ) -> void
            | (
              ?OpenTransit::Models::AgenciesWithCoverageListResponse::Data::list
              | OpenTransit::BaseModel data
            ) -> void

          def to_hash: -> OpenTransit::Models::AgenciesWithCoverageListResponse::Data::list
        end
      end
    end
  end
end
