module OpenTransit
  module Models
    type arrival_and_departure_list_params =
      { minutes_after: Integer, minutes_before: Integer, time: Time }
      & OpenTransit::request_parameters

    class ArrivalAndDepartureListParams < OpenTransit::BaseModel
      extend OpenTransit::RequestParameters::Converter
      include OpenTransit::RequestParameters

      attr_reader minutes_after: Integer?

      def minutes_after=: (Integer) -> void

      attr_reader minutes_before: Integer?

      def minutes_before=: (Integer) -> void

      attr_reader time: Time?

      def time=: (Time) -> void

      def initialize:
        (
          minutes_after: Integer,
          minutes_before: Integer,
          time: Time,
          request_options: OpenTransit::request_opts
        ) -> void
        | (
          ?OpenTransit::Models::arrival_and_departure_list_params
          | OpenTransit::BaseModel data
        ) -> void

      def to_hash: -> OpenTransit::Models::arrival_and_departure_list_params
    end
  end
end
