module OpenTransit
  module Models
    type block_retrieve_params = {  } & OpenTransit::request_parameters

    class BlockRetrieveParams < OpenTransit::BaseModel
      extend OpenTransit::RequestParameters::Converter
      include OpenTransit::RequestParameters

      def initialize:
        (request_options: OpenTransit::request_opts) -> void
        | (
          ?OpenTransit::Models::block_retrieve_params
          | OpenTransit::BaseModel data
        ) -> void

      def to_hash: -> OpenTransit::Models::block_retrieve_params
    end
  end
end
