module OpenTransit
  module Models
    type route_ids_for_agency_list_response =
      { data: OpenTransit::Models::RouteIDsForAgencyListResponse::Data }

    class RouteIDsForAgencyListResponse < OpenTransit::Models::ResponseWrapper
      attr_accessor data: OpenTransit::Models::RouteIDsForAgencyListResponse::Data

      def initialize:
        (data: OpenTransit::Models::RouteIDsForAgencyListResponse::Data) -> void
        | (
          ?OpenTransit::Models::route_ids_for_agency_list_response
          | OpenTransit::BaseModel data
        ) -> void

      def to_hash: -> OpenTransit::Models::route_ids_for_agency_list_response

      type data =
        {
          limit_exceeded: bool,
          list: Array[String],
          references: OpenTransit::Models::References
        }

      class Data < OpenTransit::BaseModel
        attr_accessor limit_exceeded: bool

        attr_accessor list: Array[String]

        attr_accessor references: OpenTransit::Models::References

        def initialize:
          (
            limit_exceeded: bool,
            list: Array[String],
            references: OpenTransit::Models::References
          ) -> void
          | (
            ?OpenTransit::Models::RouteIDsForAgencyListResponse::data
            | OpenTransit::BaseModel data
          ) -> void

        def to_hash: -> OpenTransit::Models::RouteIDsForAgencyListResponse::data
      end
    end
  end
end
