module OpenTransit
  module Models
    type schedule_for_route_retrieve_params =
      { date: Date } & OpenTransit::request_parameters

    class ScheduleForRouteRetrieveParams < OpenTransit::BaseModel
      extend OpenTransit::RequestParameters::Converter
      include OpenTransit::RequestParameters

      attr_reader date: Date?

      def date=: (Date) -> void

      def initialize:
        (date: Date, request_options: OpenTransit::request_opts) -> void
        | (
          ?OpenTransit::Models::schedule_for_route_retrieve_params
          | OpenTransit::BaseModel data
        ) -> void

      def to_hash: -> OpenTransit::Models::schedule_for_route_retrieve_params
    end
  end
end
