module OpenTransit
  module Models
    type stops_for_route_list_params =
      { include_polylines: bool, time: String }
      & OpenTransit::request_parameters

    class StopsForRouteListParams < OpenTransit::BaseModel
      extend OpenTransit::RequestParameters::Converter
      include OpenTransit::RequestParameters

      attr_reader include_polylines: bool?

      def include_polylines=: (bool) -> void

      attr_reader time: String?

      def time=: (String) -> void

      def initialize:
        (
          include_polylines: bool,
          time: String,
          request_options: OpenTransit::request_opts
        ) -> void
        | (
          ?OpenTransit::Models::stops_for_route_list_params
          | OpenTransit::BaseModel data
        ) -> void

      def to_hash: -> OpenTransit::Models::stops_for_route_list_params
    end
  end
end
