module OpenTransit
  module Models
    type trips_for_location_list_params =
      {
        lat: Float,
        lat_span: Float,
        lon: Float,
        lon_span: Float,
        include_schedule: bool,
        include_trip: bool,
        time: Integer
      }
      & OpenTransit::request_parameters

    class TripsForLocationListParams < OpenTransit::BaseModel
      extend OpenTransit::RequestParameters::Converter
      include OpenTransit::RequestParameters

      attr_accessor lat: Float

      attr_accessor lat_span: Float

      attr_accessor lon: Float

      attr_accessor lon_span: Float

      attr_reader include_schedule: bool?

      def include_schedule=: (bool) -> void

      attr_reader include_trip: bool?

      def include_trip=: (bool) -> void

      attr_reader time: Integer?

      def time=: (Integer) -> void

      def initialize:
        (
          lat: Float,
          lat_span: Float,
          lon: Float,
          lon_span: Float,
          include_schedule: bool,
          include_trip: bool,
          time: Integer,
          request_options: OpenTransit::request_opts
        ) -> void
        | (
          ?OpenTransit::Models::trips_for_location_list_params
          | OpenTransit::BaseModel data
        ) -> void

      def to_hash: -> OpenTransit::Models::trips_for_location_list_params
    end
  end
end
