# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) && caller.chain([$PROGRAM_NAME]).chain(ARGV).grep(/tapioca/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "open_transit/version"
require_relative "open_transit/internal/util"
require_relative "open_transit/internal/type/converter"
require_relative "open_transit/internal/type/unknown"
require_relative "open_transit/internal/type/boolean"
require_relative "open_transit/internal/type/file_input"
require_relative "open_transit/internal/type/enum"
require_relative "open_transit/internal/type/union"
require_relative "open_transit/internal/type/array_of"
require_relative "open_transit/internal/type/hash_of"
require_relative "open_transit/internal/type/base_model"
require_relative "open_transit/internal/type/base_page"
require_relative "open_transit/internal/type/request_parameters"
require_relative "open_transit/internal"
require_relative "open_transit/request_options"
require_relative "open_transit/file_part"
require_relative "open_transit/errors"
require_relative "open_transit/internal/transport/base_client"
require_relative "open_transit/internal/transport/pooled_net_requester"
require_relative "open_transit/client"
require_relative "open_transit/models/response_wrapper"
require_relative "open_transit/models/agencies_with_coverage_list_params"
require_relative "open_transit/models/agencies_with_coverage_list_response"
require_relative "open_transit/models/agency_retrieve_params"
require_relative "open_transit/models/agency_retrieve_response"
require_relative "open_transit/models/arrival_and_departure_list_params"
require_relative "open_transit/models/arrival_and_departure_list_response"
require_relative "open_transit/models/arrival_and_departure_retrieve_params"
require_relative "open_transit/models/arrival_and_departure_retrieve_response"
require_relative "open_transit/models/block_retrieve_params"
require_relative "open_transit/models/block_retrieve_response"
require_relative "open_transit/models/config_retrieve_params"
require_relative "open_transit/models/config_retrieve_response"
require_relative "open_transit/models/current_time_retrieve_params"
require_relative "open_transit/models/current_time_retrieve_response"
require_relative "open_transit/models/references"
require_relative "open_transit/models/report_problem_with_stop_retrieve_params"
require_relative "open_transit/models/report_problem_with_trip_retrieve_params"
require_relative "open_transit/models/route_ids_for_agency_list_params"
require_relative "open_transit/models/route_ids_for_agency_list_response"
require_relative "open_transit/models/route_retrieve_params"
require_relative "open_transit/models/route_retrieve_response"
require_relative "open_transit/models/routes_for_agency_list_params"
require_relative "open_transit/models/routes_for_agency_list_response"
require_relative "open_transit/models/routes_for_location_list_params"
require_relative "open_transit/models/routes_for_location_list_response"
require_relative "open_transit/models/schedule_for_route_retrieve_params"
require_relative "open_transit/models/schedule_for_route_retrieve_response"
require_relative "open_transit/models/schedule_for_stop_retrieve_params"
require_relative "open_transit/models/schedule_for_stop_retrieve_response"
require_relative "open_transit/models/search_for_route_list_params"
require_relative "open_transit/models/search_for_route_list_response"
require_relative "open_transit/models/search_for_stop_list_params"
require_relative "open_transit/models/search_for_stop_list_response"
require_relative "open_transit/models/shape_retrieve_params"
require_relative "open_transit/models/shape_retrieve_response"
require_relative "open_transit/models/stop_ids_for_agency_list_params"
require_relative "open_transit/models/stop_ids_for_agency_list_response"
require_relative "open_transit/models/stop_retrieve_params"
require_relative "open_transit/models/stop_retrieve_response"
require_relative "open_transit/models/stops_for_agency_list_params"
require_relative "open_transit/models/stops_for_agency_list_response"
require_relative "open_transit/models/stops_for_location_list_params"
require_relative "open_transit/models/stops_for_location_list_response"
require_relative "open_transit/models/stops_for_route_list_params"
require_relative "open_transit/models/stops_for_route_list_response"
require_relative "open_transit/models/trip_detail_retrieve_params"
require_relative "open_transit/models/trip_detail_retrieve_response"
require_relative "open_transit/models/trip_for_vehicle_retrieve_params"
require_relative "open_transit/models/trip_for_vehicle_retrieve_response"
require_relative "open_transit/models/trip_retrieve_params"
require_relative "open_transit/models/trip_retrieve_response"
require_relative "open_transit/models/trips_for_location_list_params"
require_relative "open_transit/models/trips_for_location_list_response"
require_relative "open_transit/models/trips_for_route_list_params"
require_relative "open_transit/models/trips_for_route_list_response"
require_relative "open_transit/models/vehicles_for_agency_list_params"
require_relative "open_transit/models/vehicles_for_agency_list_response"
require_relative "open_transit/models"
require_relative "open_transit/resources/agencies_with_coverage"
require_relative "open_transit/resources/agency"
require_relative "open_transit/resources/arrival_and_departure"
require_relative "open_transit/resources/block"
require_relative "open_transit/resources/config"
require_relative "open_transit/resources/current_time"
require_relative "open_transit/resources/report_problem_with_stop"
require_relative "open_transit/resources/report_problem_with_trip"
require_relative "open_transit/resources/route"
require_relative "open_transit/resources/route_ids_for_agency"
require_relative "open_transit/resources/routes_for_agency"
require_relative "open_transit/resources/routes_for_location"
require_relative "open_transit/resources/schedule_for_route"
require_relative "open_transit/resources/schedule_for_stop"
require_relative "open_transit/resources/search_for_route"
require_relative "open_transit/resources/search_for_stop"
require_relative "open_transit/resources/shape"
require_relative "open_transit/resources/stop"
require_relative "open_transit/resources/stop_ids_for_agency"
require_relative "open_transit/resources/stops_for_agency"
require_relative "open_transit/resources/stops_for_location"
require_relative "open_transit/resources/stops_for_route"
require_relative "open_transit/resources/trip"
require_relative "open_transit/resources/trip_details"
require_relative "open_transit/resources/trip_for_vehicle"
require_relative "open_transit/resources/trips_for_location"
require_relative "open_transit/resources/trips_for_route"
require_relative "open_transit/resources/vehicles_for_agency"
