module OnebusawaySDK
  module Models
    type agency_retrieve_params = {  } & OnebusawaySDK::request_parameters

    class AgencyRetrieveParams < OnebusawaySDK::BaseModel
      extend OnebusawaySDK::Type::RequestParameters::Converter
      include OnebusawaySDK::RequestParameters

      def initialize: (?request_options: OnebusawaySDK::request_opts) -> void

      def to_hash: -> OnebusawaySDK::Models::agency_retrieve_params
    end
  end
end
