module OnebusawaySDK
  module Models
    type config_retrieve_params = {  } & OnebusawaySDK::request_parameters

    class ConfigRetrieveParams < OnebusawaySDK::BaseModel
      extend OnebusawaySDK::RequestParameters::Converter
      include OnebusawaySDK::RequestParameters

      def initialize:
        (?request_options: OnebusawaySDK::request_opts) -> void
        | (
          ?OnebusawaySDK::Models::config_retrieve_params
          | OnebusawaySDK::BaseModel data
        ) -> void

      def to_hash: -> OnebusawaySDK::Models::config_retrieve_params
    end
  end
end
