module OnebusawaySDK
  module Models
    type current_time_retrieve_response =
      { data: OnebusawaySDK::Models::CurrentTimeRetrieveResponse::Data }

    class CurrentTimeRetrieveResponse < OnebusawaySDK::Models::ResponseWrapper
      attr_accessor data: OnebusawaySDK::Models::CurrentTimeRetrieveResponse::Data

      def initialize:
        (data: OnebusawaySDK::Models::CurrentTimeRetrieveResponse::Data) -> void
        | (
          ?OnebusawaySDK::Models::current_time_retrieve_response
          | OnebusawaySDK::BaseModel data
        ) -> void

      def to_hash: -> OnebusawaySDK::Models::current_time_retrieve_response

      type data =
        {
          entry: OnebusawaySDK::Models::CurrentTimeRetrieveResponse::Data::Entry,
          references: OnebusawaySDK::Models::References
        }

      class Data < OnebusawaySDK::BaseModel
        attr_accessor entry: OnebusawaySDK::Models::CurrentTimeRetrieveResponse::Data::Entry

        attr_accessor references: OnebusawaySDK::Models::References

        def initialize:
          (
            entry: OnebusawaySDK::Models::CurrentTimeRetrieveResponse::Data::Entry,
            references: OnebusawaySDK::Models::References
          ) -> void
          | (
            ?OnebusawaySDK::Models::CurrentTimeRetrieveResponse::data
            | OnebusawaySDK::BaseModel data
          ) -> void

        def to_hash: -> OnebusawaySDK::Models::CurrentTimeRetrieveResponse::data

        type entry = { readable_time: String, time: Integer }

        class Entry < OnebusawaySDK::BaseModel
          attr_reader readable_time: String?

          def readable_time=: (String) -> String

          attr_reader time: Integer?

          def time=: (Integer) -> Integer

          def initialize:
            (readable_time: String, time: Integer) -> void
            | (
              ?OnebusawaySDK::Models::CurrentTimeRetrieveResponse::Data::entry
              | OnebusawaySDK::BaseModel data
            ) -> void

          def to_hash: -> OnebusawaySDK::Models::CurrentTimeRetrieveResponse::Data::entry
        end
      end
    end
  end
end
