module OnebusawaySDK
  module Models
    type report_problem_with_trip_retrieve_params =
      {
        code: OnebusawaySDK::Models::ReportProblemWithTripRetrieveParams::code,
        service_date: Integer,
        stop_id: String,
        user_comment: String,
        user_lat: Float,
        user_location_accuracy: Float,
        user_lon: Float,
        user_on_vehicle: bool,
        user_vehicle_number: String,
        vehicle_id: String
      }
      & OnebusawaySDK::request_parameters

    class ReportProblemWithTripRetrieveParams < OnebusawaySDK::BaseModel
      extend OnebusawaySDK::RequestParameters::Converter
      include OnebusawaySDK::RequestParameters

      attr_reader code: OnebusawaySDK::Models::ReportProblemWithTripRetrieveParams::code?

      def code=: (
        OnebusawaySDK::Models::ReportProblemWithTripRetrieveParams::code
      ) -> void

      attr_reader service_date: Integer?

      def service_date=: (Integer) -> void

      attr_reader stop_id: String?

      def stop_id=: (String) -> void

      attr_reader user_comment: String?

      def user_comment=: (String) -> void

      attr_reader user_lat: Float?

      def user_lat=: (Float) -> void

      attr_reader user_location_accuracy: Float?

      def user_location_accuracy=: (Float) -> void

      attr_reader user_lon: Float?

      def user_lon=: (Float) -> void

      attr_reader user_on_vehicle: bool?

      def user_on_vehicle=: (bool) -> void

      attr_reader user_vehicle_number: String?

      def user_vehicle_number=: (String) -> void

      attr_reader vehicle_id: String?

      def vehicle_id=: (String) -> void

      def initialize:
        (
          code: OnebusawaySDK::Models::ReportProblemWithTripRetrieveParams::code,
          service_date: Integer,
          stop_id: String,
          user_comment: String,
          user_lat: Float,
          user_location_accuracy: Float,
          user_lon: Float,
          user_on_vehicle: bool,
          user_vehicle_number: String,
          vehicle_id: String,
          request_options: OnebusawaySDK::request_opts
        ) -> void
        | (
          ?OnebusawaySDK::Models::report_problem_with_trip_retrieve_params
          | OnebusawaySDK::BaseModel data
        ) -> void

      def to_hash: -> OnebusawaySDK::Models::report_problem_with_trip_retrieve_params

      type code =
        :vehicle_never_came
        | :vehicle_came_early
        | :vehicle_came_late
        | :wrong_headsign
        | :vehicle_does_not_stop_here
        | :other

      class Code < OnebusawaySDK::Enum
        VEHICLE_NEVER_CAME: :vehicle_never_came
        VEHICLE_CAME_EARLY: :vehicle_came_early
        VEHICLE_CAME_LATE: :vehicle_came_late
        WRONG_HEADSIGN: :wrong_headsign
        VEHICLE_DOES_NOT_STOP_HERE: :vehicle_does_not_stop_here
        OTHER: :other

        def self.values: -> ::Array[OnebusawaySDK::Models::ReportProblemWithTripRetrieveParams::code]
      end
    end
  end
end
