module OnebusawaySDK
  module Models
    type route_ids_for_agency_list_params =
      {  } & OnebusawaySDK::request_parameters

    class RouteIDsForAgencyListParams < OnebusawaySDK::BaseModel
      extend OnebusawaySDK::RequestParameters::Converter
      include OnebusawaySDK::RequestParameters

      def initialize:
        (request_options: OnebusawaySDK::request_opts) -> void
        | (
          ?OnebusawaySDK::Models::route_ids_for_agency_list_params
          | OnebusawaySDK::BaseModel data
        ) -> void

      def to_hash: -> OnebusawaySDK::Models::route_ids_for_agency_list_params
    end
  end
end
