module OnebusawaySDK
  module Models
    type route_ids_for_agency_list_response =
      { data: OnebusawaySDK::Models::RouteIDsForAgencyListResponse::Data }

    class RouteIDsForAgencyListResponse < OnebusawaySDK::Models::ResponseWrapper
      attr_accessor data: OnebusawaySDK::Models::RouteIDsForAgencyListResponse::Data

      def initialize:
        (
          data: OnebusawaySDK::Models::RouteIDsForAgencyListResponse::Data
        ) -> void
        | (
          ?OnebusawaySDK::Models::route_ids_for_agency_list_response
          | OnebusawaySDK::BaseModel data
        ) -> void

      def to_hash: -> OnebusawaySDK::Models::route_ids_for_agency_list_response

      type data =
        {
          limit_exceeded: bool,
          list: ::Array[String],
          references: OnebusawaySDK::Models::References
        }

      class Data < OnebusawaySDK::BaseModel
        attr_accessor limit_exceeded: bool

        attr_accessor list: ::Array[String]

        attr_accessor references: OnebusawaySDK::Models::References

        def initialize:
          (
            limit_exceeded: bool,
            list: ::Array[String],
            references: OnebusawaySDK::Models::References
          ) -> void
          | (
            ?OnebusawaySDK::Models::RouteIDsForAgencyListResponse::data
            | OnebusawaySDK::BaseModel data
          ) -> void

        def to_hash: -> OnebusawaySDK::Models::RouteIDsForAgencyListResponse::data
      end
    end
  end
end
