module OnebusawaySDK
  module Models
    type routes_for_location_list_response =
      { data: OnebusawaySDK::Models::RoutesForLocationListResponse::Data }

    class RoutesForLocationListResponse < OnebusawaySDK::Models::ResponseWrapper
      attr_accessor data: OnebusawaySDK::Models::RoutesForLocationListResponse::Data

      def initialize:
        (
          data: OnebusawaySDK::Models::RoutesForLocationListResponse::Data
        ) -> void
        | (
          ?OnebusawaySDK::Models::routes_for_location_list_response
          | OnebusawaySDK::BaseModel data
        ) -> void

      def to_hash: -> OnebusawaySDK::Models::routes_for_location_list_response

      type data =
        {
          limit_exceeded: bool,
          list: ::Array[OnebusawaySDK::Models::RoutesForLocationListResponse::Data::List],
          out_of_range: bool,
          references: OnebusawaySDK::Models::References
        }

      class Data < OnebusawaySDK::BaseModel
        attr_accessor limit_exceeded: bool

        attr_accessor list: ::Array[OnebusawaySDK::Models::RoutesForLocationListResponse::Data::List]

        attr_accessor out_of_range: bool

        attr_accessor references: OnebusawaySDK::Models::References

        def initialize:
          (
            limit_exceeded: bool,
            list: ::Array[OnebusawaySDK::Models::RoutesForLocationListResponse::Data::List],
            out_of_range: bool,
            references: OnebusawaySDK::Models::References
          ) -> void
          | (
            ?OnebusawaySDK::Models::RoutesForLocationListResponse::data
            | OnebusawaySDK::BaseModel data
          ) -> void

        def to_hash: -> OnebusawaySDK::Models::RoutesForLocationListResponse::data

        type list =
          {
            id: String,
            agency_id: String,
            type: Integer,
            color: String,
            description: String,
            long_name: String,
            null_safe_short_name: String,
            short_name: String,
            text_color: String,
            url: String
          }

        class List < OnebusawaySDK::BaseModel
          attr_accessor id: String

          attr_accessor agency_id: String

          attr_accessor type: Integer

          attr_reader color: String?

          def color=: (String) -> void

          attr_reader description: String?

          def description=: (String) -> void

          attr_reader long_name: String?

          def long_name=: (String) -> void

          attr_reader null_safe_short_name: String?

          def null_safe_short_name=: (String) -> void

          attr_reader short_name: String?

          def short_name=: (String) -> void

          attr_reader text_color: String?

          def text_color=: (String) -> void

          attr_reader url: String?

          def url=: (String) -> void

          def initialize:
            (
              id: String,
              agency_id: String,
              type: Integer,
              color: String,
              description: String,
              long_name: String,
              null_safe_short_name: String,
              short_name: String,
              text_color: String,
              url: String
            ) -> void
            | (
              ?OnebusawaySDK::Models::RoutesForLocationListResponse::Data::list
              | OnebusawaySDK::BaseModel data
            ) -> void

          def to_hash: -> OnebusawaySDK::Models::RoutesForLocationListResponse::Data::list
        end
      end
    end
  end
end
