module OnebusawaySDK
  module Models
    type search_for_stop_list_params =
      { input: String, max_count: Integer } & OnebusawaySDK::request_parameters

    class SearchForStopListParams < OnebusawaySDK::BaseModel
      extend OnebusawaySDK::RequestParameters::Converter
      include OnebusawaySDK::RequestParameters

      attr_accessor input: String

      attr_reader max_count: Integer?

      def max_count=: (Integer) -> Integer

      def initialize:
        (
          input: String,
          ?max_count: Integer,
          ?request_options: OnebusawaySDK::request_opts
        ) -> void
        | (
          ?OnebusawaySDK::Models::search_for_stop_list_params
          | OnebusawaySDK::BaseModel data
        ) -> void

      def to_hash: -> OnebusawaySDK::Models::search_for_stop_list_params
    end
  end
end
