module OnebusawaySDK
  module Models
    type shape_retrieve_response =
      { data: OnebusawaySDK::Models::ShapeRetrieveResponse::Data }

    class ShapeRetrieveResponse < OnebusawaySDK::Models::ResponseWrapper
      def data: -> OnebusawaySDK::Models::ShapeRetrieveResponse::Data

      def data=: (
        OnebusawaySDK::Models::ShapeRetrieveResponse::Data _
      ) -> OnebusawaySDK::Models::ShapeRetrieveResponse::Data

      def initialize:
        (data: OnebusawaySDK::Models::ShapeRetrieveResponse::Data) -> void
        | (
          ?OnebusawaySDK::Models::shape_retrieve_response
          | OnebusawaySDK::BaseModel data
        ) -> void

      def to_hash: -> OnebusawaySDK::Models::shape_retrieve_response

      type data =
        {
          entry: OnebusawaySDK::Models::ShapeRetrieveResponse::Data::Entry,
          references: OnebusawaySDK::Models::References
        }

      class Data < OnebusawaySDK::BaseModel
        attr_accessor entry: OnebusawaySDK::Models::ShapeRetrieveResponse::Data::Entry

        attr_accessor references: OnebusawaySDK::Models::References

        def initialize:
          (
            entry: OnebusawaySDK::Models::ShapeRetrieveResponse::Data::Entry,
            references: OnebusawaySDK::Models::References
          ) -> void
          | (
            ?OnebusawaySDK::Models::ShapeRetrieveResponse::data
            | OnebusawaySDK::BaseModel data
          ) -> void

        def to_hash: -> OnebusawaySDK::Models::ShapeRetrieveResponse::data

        type entry = { length: Integer, points: String, levels: String }

        class Entry < OnebusawaySDK::BaseModel
          attr_accessor length: Integer

          attr_accessor points: String

          attr_reader levels: String?

          def levels=: (String) -> String

          def initialize:
            (length: Integer, points: String, ?levels: String) -> void
            | (
              ?OnebusawaySDK::Models::ShapeRetrieveResponse::Data::entry
              | OnebusawaySDK::BaseModel data
            ) -> void

          def to_hash: -> OnebusawaySDK::Models::ShapeRetrieveResponse::Data::entry
        end
      end
    end
  end
end
