module OnebusawaySDK
  module Models
    type stops_for_route_list_params =
      { include_polylines: bool, time: String }
      & OnebusawaySDK::request_parameters

    class StopsForRouteListParams < OnebusawaySDK::BaseModel
      extend OnebusawaySDK::Type::RequestParameters::Converter
      include OnebusawaySDK::RequestParameters

      attr_reader include_polylines: bool?

      def include_polylines=: (bool) -> bool

      attr_reader time: String?

      def time=: (String) -> String

      def initialize: (
        ?include_polylines: bool,
        ?time: String,
        ?request_options: OnebusawaySDK::request_opts
      ) -> void

      def to_hash: -> OnebusawaySDK::Models::stops_for_route_list_params
    end
  end
end
