module OnebusawaySDK
  module Models
    type stops_for_agency_list_response =
      {
        limit_exceeded: bool,
        list: ::Array[OnebusawaySDK::Models::StopsForAgencyListResponse::List],
        references: OnebusawaySDK::Models::References,
        out_of_range: bool
      }

    class StopsForAgencyListResponse < OnebusawaySDK::Models::ResponseWrapper
      def limit_exceeded: -> bool

      def limit_exceeded=: (bool _) -> bool

      def list: -> ::Array[OnebusawaySDK::Models::StopsForAgencyListResponse::List]

      def list=: (
        ::Array[OnebusawaySDK::Models::StopsForAgencyListResponse::List] _
      ) -> ::Array[OnebusawaySDK::Models::StopsForAgencyListResponse::List]

      def references: -> OnebusawaySDK::Models::References

      def references=: (
        OnebusawaySDK::Models::References _
      ) -> OnebusawaySDK::Models::References

      def out_of_range: -> bool?

      def out_of_range=: (bool _) -> bool

      def initialize:
        (
          limit_exceeded: bool,
          list: ::Array[OnebusawaySDK::Models::StopsForAgencyListResponse::List],
          references: OnebusawaySDK::Models::References,
          out_of_range: bool
        ) -> void
        | (
          ?OnebusawaySDK::Models::stops_for_agency_list_response
          | OnebusawaySDK::BaseModel data
        ) -> void

      def to_hash: -> OnebusawaySDK::Models::stops_for_agency_list_response

      type list =
        {
          id: String,
          lat: Float,
          lon: Float,
          name: String,
          parent: String,
          route_ids: ::Array[String],
          static_route_ids: ::Array[String],
          code: String,
          direction: String,
          location_type: Integer,
          wheelchair_boarding: String
        }

      class List < OnebusawaySDK::BaseModel
        attr_accessor id: String

        attr_accessor lat: Float

        attr_accessor lon: Float

        attr_accessor name: String

        attr_accessor parent: String

        attr_accessor route_ids: ::Array[String]

        attr_accessor static_route_ids: ::Array[String]

        attr_reader code: String?

        def code=: (String) -> String

        attr_reader direction: String?

        def direction=: (String) -> String

        attr_reader location_type: Integer?

        def location_type=: (Integer) -> Integer

        attr_reader wheelchair_boarding: String?

        def wheelchair_boarding=: (String) -> String

        def initialize:
          (
            id: String,
            lat: Float,
            lon: Float,
            name: String,
            parent: String,
            route_ids: ::Array[String],
            static_route_ids: ::Array[String],
            code: String,
            direction: String,
            location_type: Integer,
            wheelchair_boarding: String
          ) -> void
          | (
            ?OnebusawaySDK::Models::StopsForAgencyListResponse::list
            | OnebusawaySDK::BaseModel data
          ) -> void

        def to_hash: -> OnebusawaySDK::Models::StopsForAgencyListResponse::list
      end
    end
  end
end
