module OnebusawaySDK
  module Models
    type stop_retrieve_params = {  } & OnebusawaySDK::request_parameters

    class StopRetrieveParams < OnebusawaySDK::BaseModel
      extend OnebusawaySDK::RequestParameters::Converter
      include OnebusawaySDK::RequestParameters

      def initialize: (?request_options: OnebusawaySDK::request_opts) -> void

      def to_hash: -> OnebusawaySDK::Models::stop_retrieve_params
    end
  end
end
