module OnebusawaySDK
  module Models
    type trips_for_location_list_response =
      { data: OnebusawaySDK::Models::TripsForLocationListResponse::Data }

    class TripsForLocationListResponse < OnebusawaySDK::Models::ResponseWrapper
      attr_accessor data: OnebusawaySDK::Models::TripsForLocationListResponse::Data

      def initialize:
        (
          data: OnebusawaySDK::Models::TripsForLocationListResponse::Data
        ) -> void
        | (
          ?OnebusawaySDK::Models::trips_for_location_list_response
          | OnebusawaySDK::BaseModel data
        ) -> void

      def to_hash: -> OnebusawaySDK::Models::trips_for_location_list_response

      type data =
        {
          limit_exceeded: bool,
          list: ::Array[OnebusawaySDK::Models::TripsForLocationListResponse::Data::List],
          references: OnebusawaySDK::Models::References,
          out_of_range: bool
        }

      class Data < OnebusawaySDK::BaseModel
        attr_accessor limit_exceeded: bool

        attr_accessor list: ::Array[OnebusawaySDK::Models::TripsForLocationListResponse::Data::List]

        attr_accessor references: OnebusawaySDK::Models::References

        attr_reader out_of_range: bool?

        def out_of_range=: (bool) -> void

        def initialize:
          (
            limit_exceeded: bool,
            list: ::Array[OnebusawaySDK::Models::TripsForLocationListResponse::Data::List],
            references: OnebusawaySDK::Models::References,
            out_of_range: bool
          ) -> void
          | (
            ?OnebusawaySDK::Models::TripsForLocationListResponse::data
            | OnebusawaySDK::BaseModel data
          ) -> void

        def to_hash: -> OnebusawaySDK::Models::TripsForLocationListResponse::data

        type list =
          {
            schedule: OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::Schedule,
            status: OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::Status,
            trip_id: String,
            frequency: String?,
            service_date: Integer,
            situation_ids: ::Array[String]
          }

        class List < OnebusawaySDK::BaseModel
          attr_accessor schedule: OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::Schedule

          attr_accessor status: OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::Status

          attr_accessor trip_id: String

          attr_accessor frequency: String?

          attr_reader service_date: Integer?

          def service_date=: (Integer) -> void

          attr_reader situation_ids: ::Array[String]?

          def situation_ids=: (::Array[String]) -> void

          def initialize:
            (
              schedule: OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::Schedule,
              status: OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::Status,
              trip_id: String,
              frequency: String?,
              service_date: Integer,
              situation_ids: ::Array[String]
            ) -> void
            | (
              ?OnebusawaySDK::Models::TripsForLocationListResponse::Data::list
              | OnebusawaySDK::BaseModel data
            ) -> void

          def to_hash: -> OnebusawaySDK::Models::TripsForLocationListResponse::Data::list

          type schedule =
            {
              next_trip_id: String,
              previous_trip_id: String,
              stop_times: ::Array[OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::Schedule::StopTime],
              time_zone: String,
              frequency: String?
            }

          class Schedule < OnebusawaySDK::BaseModel
            attr_accessor next_trip_id: String

            attr_accessor previous_trip_id: String

            attr_accessor stop_times: ::Array[OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::Schedule::StopTime]

            attr_accessor time_zone: String

            attr_accessor frequency: String?

            def initialize:
              (
                next_trip_id: String,
                previous_trip_id: String,
                stop_times: ::Array[OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::Schedule::StopTime],
                time_zone: String,
                frequency: String?
              ) -> void
              | (
                ?OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::schedule
                | OnebusawaySDK::BaseModel data
              ) -> void

            def to_hash: -> OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::schedule

            type stop_time =
              {
                arrival_time: Integer,
                departure_time: Integer,
                distance_along_trip: Float,
                historical_occupancy: String,
                stop_headsign: String,
                stop_id: String
              }

            class StopTime < OnebusawaySDK::BaseModel
              attr_reader arrival_time: Integer?

              def arrival_time=: (Integer) -> void

              attr_reader departure_time: Integer?

              def departure_time=: (Integer) -> void

              attr_reader distance_along_trip: Float?

              def distance_along_trip=: (Float) -> void

              attr_reader historical_occupancy: String?

              def historical_occupancy=: (String) -> void

              attr_reader stop_headsign: String?

              def stop_headsign=: (String) -> void

              attr_reader stop_id: String?

              def stop_id=: (String) -> void

              def initialize:
                (
                  arrival_time: Integer,
                  departure_time: Integer,
                  distance_along_trip: Float,
                  historical_occupancy: String,
                  stop_headsign: String,
                  stop_id: String
                ) -> void
                | (
                  ?OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::Schedule::stop_time
                  | OnebusawaySDK::BaseModel data
                ) -> void

              def to_hash: -> OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::Schedule::stop_time
            end
          end

          type status =
            {
              active_trip_id: String,
              block_trip_sequence: Integer,
              closest_stop: String,
              distance_along_trip: Float,
              last_known_distance_along_trip: Float,
              last_location_update_time: Integer,
              last_update_time: Integer,
              occupancy_capacity: Integer,
              occupancy_count: Integer,
              occupancy_status: String,
              phase: String,
              predicted: bool,
              schedule_deviation: Integer,
              service_date: Integer,
              status: String,
              total_distance_along_trip: Float,
              closest_stop_time_offset: Integer,
              frequency: String,
              last_known_location: OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::Status::LastKnownLocation,
              last_known_orientation: Float,
              next_stop: String,
              next_stop_time_offset: Integer,
              orientation: Float,
              position: OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::Status::Position,
              scheduled_distance_along_trip: Float,
              situation_ids: ::Array[String],
              vehicle_id: String
            }

          class Status < OnebusawaySDK::BaseModel
            attr_accessor active_trip_id: String

            attr_accessor block_trip_sequence: Integer

            attr_accessor closest_stop: String

            attr_accessor distance_along_trip: Float

            attr_accessor last_known_distance_along_trip: Float

            attr_accessor last_location_update_time: Integer

            attr_accessor last_update_time: Integer

            attr_accessor occupancy_capacity: Integer

            attr_accessor occupancy_count: Integer

            attr_accessor occupancy_status: String

            attr_accessor phase: String

            attr_accessor predicted: bool

            attr_accessor schedule_deviation: Integer

            attr_accessor service_date: Integer

            attr_accessor status: String

            attr_accessor total_distance_along_trip: Float

            attr_reader closest_stop_time_offset: Integer?

            def closest_stop_time_offset=: (Integer) -> void

            attr_reader frequency: String?

            def frequency=: (String) -> void

            attr_reader last_known_location: OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::Status::LastKnownLocation?

            def last_known_location=: (
              OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::Status::LastKnownLocation
            ) -> void

            attr_reader last_known_orientation: Float?

            def last_known_orientation=: (Float) -> void

            attr_reader next_stop: String?

            def next_stop=: (String) -> void

            attr_reader next_stop_time_offset: Integer?

            def next_stop_time_offset=: (Integer) -> void

            attr_reader orientation: Float?

            def orientation=: (Float) -> void

            attr_reader position: OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::Status::Position?

            def position=: (
              OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::Status::Position
            ) -> void

            attr_reader scheduled_distance_along_trip: Float?

            def scheduled_distance_along_trip=: (Float) -> void

            attr_reader situation_ids: ::Array[String]?

            def situation_ids=: (::Array[String]) -> void

            attr_reader vehicle_id: String?

            def vehicle_id=: (String) -> void

            def initialize:
              (
                active_trip_id: String,
                block_trip_sequence: Integer,
                closest_stop: String,
                distance_along_trip: Float,
                last_known_distance_along_trip: Float,
                last_location_update_time: Integer,
                last_update_time: Integer,
                occupancy_capacity: Integer,
                occupancy_count: Integer,
                occupancy_status: String,
                phase: String,
                predicted: bool,
                schedule_deviation: Integer,
                service_date: Integer,
                status: String,
                total_distance_along_trip: Float,
                closest_stop_time_offset: Integer,
                frequency: String,
                last_known_location: OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::Status::LastKnownLocation,
                last_known_orientation: Float,
                next_stop: String,
                next_stop_time_offset: Integer,
                orientation: Float,
                position: OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::Status::Position,
                scheduled_distance_along_trip: Float,
                situation_ids: ::Array[String],
                vehicle_id: String
              ) -> void
              | (
                ?OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::status
                | OnebusawaySDK::BaseModel data
              ) -> void

            def to_hash: -> OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::status

            type last_known_location = { lat: Float, lon: Float }

            class LastKnownLocation < OnebusawaySDK::BaseModel
              attr_reader lat: Float?

              def lat=: (Float) -> void

              attr_reader lon: Float?

              def lon=: (Float) -> void

              def initialize:
                (lat: Float, lon: Float) -> void
                | (
                  ?OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::Status::last_known_location
                  | OnebusawaySDK::BaseModel data
                ) -> void

              def to_hash: -> OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::Status::last_known_location
            end

            type position = { lat: Float, lon: Float }

            class Position < OnebusawaySDK::BaseModel
              attr_reader lat: Float?

              def lat=: (Float) -> void

              attr_reader lon: Float?

              def lon=: (Float) -> void

              def initialize:
                (lat: Float, lon: Float) -> void
                | (
                  ?OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::Status::position
                  | OnebusawaySDK::BaseModel data
                ) -> void

              def to_hash: -> OnebusawaySDK::Models::TripsForLocationListResponse::Data::List::Status::position
            end
          end
        end
      end
    end
  end
end
