module OnebusawaySDK
  module Internal
    module Type
      class Boolean
        extend OnebusawaySDK::Internal::Type::Converter
        extend OnebusawaySDK::Internal::Util::SorbetRuntimeSupport

        def self.===: (top other) -> bool

        def self.==: (top other) -> bool

        def self.coerce: (
          bool | top value,
          state: OnebusawaySDK::Internal::Type::Converter::coerce_state
        ) -> (bool | top)

        def self.dump: (
          bool | top value,
          state: OnebusawaySDK::Internal::Type::Converter::dump_state
        ) -> (bool | top)

        def self.to_sorbet_type: -> top
      end
    end
  end
end
