module Onebusaway
  module Models
    type block_retrieve_response =
      { data: Onebusaway::Models::BlockRetrieveResponse::Data }

    class BlockRetrieveResponse < Onebusaway::Models::ResponseWrapper
      attr_accessor data: Onebusaway::Models::BlockRetrieveResponse::Data

      def initialize:
        (data: Onebusaway::Models::BlockRetrieveResponse::Data) -> void
        | (
          ?Onebusaway::Models::block_retrieve_response
          | Onebusaway::BaseModel data
        ) -> void

      def to_hash: -> Onebusaway::Models::block_retrieve_response

      type data =
        {
          entry: Onebusaway::Models::BlockRetrieveResponse::Data::Entry,
          references: Onebusaway::Models::References
        }

      class Data < Onebusaway::BaseModel
        attr_accessor entry: Onebusaway::Models::BlockRetrieveResponse::Data::Entry

        attr_accessor references: Onebusaway::Models::References

        def initialize:
          (
            entry: Onebusaway::Models::BlockRetrieveResponse::Data::Entry,
            references: Onebusaway::Models::References
          ) -> void
          | (
            ?Onebusaway::Models::BlockRetrieveResponse::data
            | Onebusaway::BaseModel data
          ) -> void

        def to_hash: -> Onebusaway::Models::BlockRetrieveResponse::data

        type entry =
          {
            id: String,
            configurations: Array[Onebusaway::Models::BlockRetrieveResponse::Data::Entry::Configuration]
          }

        class Entry < Onebusaway::BaseModel
          attr_accessor id: String

          attr_accessor configurations: Array[Onebusaway::Models::BlockRetrieveResponse::Data::Entry::Configuration]

          def initialize:
            (
              id: String,
              configurations: Array[Onebusaway::Models::BlockRetrieveResponse::Data::Entry::Configuration]
            ) -> void
            | (
              ?Onebusaway::Models::BlockRetrieveResponse::Data::entry
              | Onebusaway::BaseModel data
            ) -> void

          def to_hash: -> Onebusaway::Models::BlockRetrieveResponse::Data::entry

          type configuration =
            {
              active_service_ids: Array[String],
              trips: Array[Onebusaway::Models::BlockRetrieveResponse::Data::Entry::Configuration::Trip],
              inactive_service_ids: Array[String]
            }

          class Configuration < Onebusaway::BaseModel
            attr_accessor active_service_ids: Array[String]

            attr_accessor trips: Array[Onebusaway::Models::BlockRetrieveResponse::Data::Entry::Configuration::Trip]

            attr_reader inactive_service_ids: Array[String]?

            def inactive_service_ids=: (Array[String]) -> void

            def initialize:
              (
                active_service_ids: Array[String],
                trips: Array[Onebusaway::Models::BlockRetrieveResponse::Data::Entry::Configuration::Trip],
                inactive_service_ids: Array[String]
              ) -> void
              | (
                ?Onebusaway::Models::BlockRetrieveResponse::Data::Entry::configuration
                | Onebusaway::BaseModel data
              ) -> void

            def to_hash: -> Onebusaway::Models::BlockRetrieveResponse::Data::Entry::configuration

            type trip =
              {
                accumulated_slack_time: Float,
                block_stop_times: Array[Onebusaway::Models::BlockRetrieveResponse::Data::Entry::Configuration::Trip::BlockStopTime],
                distance_along_block: Float,
                trip_id: String
              }

            class Trip < Onebusaway::BaseModel
              attr_accessor accumulated_slack_time: Float

              attr_accessor block_stop_times: Array[Onebusaway::Models::BlockRetrieveResponse::Data::Entry::Configuration::Trip::BlockStopTime]

              attr_accessor distance_along_block: Float

              attr_accessor trip_id: String

              def initialize:
                (
                  accumulated_slack_time: Float,
                  block_stop_times: Array[Onebusaway::Models::BlockRetrieveResponse::Data::Entry::Configuration::Trip::BlockStopTime],
                  distance_along_block: Float,
                  trip_id: String
                ) -> void
                | (
                  ?Onebusaway::Models::BlockRetrieveResponse::Data::Entry::Configuration::trip
                  | Onebusaway::BaseModel data
                ) -> void

              def to_hash: -> Onebusaway::Models::BlockRetrieveResponse::Data::Entry::Configuration::trip

              type block_stop_time =
                {
                  accumulated_slack_time: Float,
                  block_sequence: Integer,
                  distance_along_block: Float,
                  stop_time: Onebusaway::Models::BlockRetrieveResponse::Data::Entry::Configuration::Trip::BlockStopTime::StopTime
                }

              class BlockStopTime < Onebusaway::BaseModel
                attr_accessor accumulated_slack_time: Float

                attr_accessor block_sequence: Integer

                attr_accessor distance_along_block: Float

                attr_accessor stop_time: Onebusaway::Models::BlockRetrieveResponse::Data::Entry::Configuration::Trip::BlockStopTime::StopTime

                def initialize:
                  (
                    accumulated_slack_time: Float,
                    block_sequence: Integer,
                    distance_along_block: Float,
                    stop_time: Onebusaway::Models::BlockRetrieveResponse::Data::Entry::Configuration::Trip::BlockStopTime::StopTime
                  ) -> void
                  | (
                    ?Onebusaway::Models::BlockRetrieveResponse::Data::Entry::Configuration::Trip::block_stop_time
                    | Onebusaway::BaseModel data
                  ) -> void

                def to_hash: -> Onebusaway::Models::BlockRetrieveResponse::Data::Entry::Configuration::Trip::block_stop_time

                type stop_time =
                  {
                    arrival_time: Integer,
                    departure_time: Integer,
                    stop_id: String,
                    drop_off_type: Integer,
                    pickup_type: Integer
                  }

                class StopTime < Onebusaway::BaseModel
                  attr_accessor arrival_time: Integer

                  attr_accessor departure_time: Integer

                  attr_accessor stop_id: String

                  attr_reader drop_off_type: Integer?

                  def drop_off_type=: (Integer) -> void

                  attr_reader pickup_type: Integer?

                  def pickup_type=: (Integer) -> void

                  def initialize:
                    (
                      arrival_time: Integer,
                      departure_time: Integer,
                      stop_id: String,
                      drop_off_type: Integer,
                      pickup_type: Integer
                    ) -> void
                    | (
                      ?Onebusaway::Models::BlockRetrieveResponse::Data::Entry::Configuration::Trip::BlockStopTime::stop_time
                      | Onebusaway::BaseModel data
                    ) -> void

                  def to_hash: -> Onebusaway::Models::BlockRetrieveResponse::Data::Entry::Configuration::Trip::BlockStopTime::stop_time
                end
              end
            end
          end
        end
      end
    end
  end
end
