module Onebusaway
  module Models
    type report_problem_with_stop_retrieve_params =
      {
        code: Onebusaway::Models::ReportProblemWithStopRetrieveParams::code,
        user_comment: String,
        user_lat: Float,
        user_location_accuracy: Float,
        user_lon: Float
      }
      & Onebusaway::request_parameters

    class ReportProblemWithStopRetrieveParams < Onebusaway::BaseModel
      extend Onebusaway::RequestParameters::Converter
      include Onebusaway::RequestParameters

      attr_reader code: Onebusaway::Models::ReportProblemWithStopRetrieveParams::code?

      def code=: (
        Onebusaway::Models::ReportProblemWithStopRetrieveParams::code
      ) -> void

      attr_reader user_comment: String?

      def user_comment=: (String) -> void

      attr_reader user_lat: Float?

      def user_lat=: (Float) -> void

      attr_reader user_location_accuracy: Float?

      def user_location_accuracy=: (Float) -> void

      attr_reader user_lon: Float?

      def user_lon=: (Float) -> void

      def initialize:
        (
          code: Onebusaway::Models::ReportProblemWithStopRetrieveParams::code,
          user_comment: String,
          user_lat: Float,
          user_location_accuracy: Float,
          user_lon: Float,
          request_options: Onebusaway::request_opts
        ) -> void
        | (
          ?Onebusaway::Models::report_problem_with_stop_retrieve_params
          | Onebusaway::BaseModel data
        ) -> void

      def to_hash: -> Onebusaway::Models::report_problem_with_stop_retrieve_params

      type code =
        :stop_name_wrong
        | :stop_number_wrong
        | :stop_location_wrong
        | :route_or_trip_missing
        | :other

      class Code < Onebusaway::Enum
        STOP_NAME_WRONG: :stop_name_wrong
        STOP_NUMBER_WRONG: :stop_number_wrong
        STOP_LOCATION_WRONG: :stop_location_wrong
        ROUTE_OR_TRIP_MISSING: :route_or_trip_missing
        OTHER: :other

        def self.values: -> ::Array[Onebusaway::Models::ReportProblemWithStopRetrieveParams::code]
      end
    end
  end
end
