module Onebusaway
  module Models
    type routes_for_agency_list_params = {  } & Onebusaway::request_parameters

    class RoutesForAgencyListParams < Onebusaway::BaseModel
      extend Onebusaway::RequestParameters::Converter
      include Onebusaway::RequestParameters

      def initialize:
        (request_options: Onebusaway::request_opts) -> void
        | (
          ?Onebusaway::Models::routes_for_agency_list_params
          | Onebusaway::BaseModel data
        ) -> void

      def to_hash: -> Onebusaway::Models::routes_for_agency_list_params
    end
  end
end
