module Onebusaway
  module Models
    type search_for_route_list_params =
      { input: String, max_count: Integer } & Onebusaway::request_parameters

    class SearchForRouteListParams < Onebusaway::BaseModel
      extend Onebusaway::RequestParameters::Converter
      include Onebusaway::RequestParameters

      attr_accessor input: String

      attr_reader max_count: Integer?

      def max_count=: (Integer) -> void

      def initialize:
        (
          input: String,
          max_count: Integer,
          request_options: Onebusaway::request_opts
        ) -> void
        | (
          ?Onebusaway::Models::search_for_route_list_params
          | Onebusaway::BaseModel data
        ) -> void

      def to_hash: -> Onebusaway::Models::search_for_route_list_params
    end
  end
end
