module Onebusaway
  module Models
    type trip_retrieve_response =
      { data: Onebusaway::Models::TripRetrieveResponse::Data }

    class TripRetrieveResponse < Onebusaway::Models::ResponseWrapper
      attr_accessor data: Onebusaway::Models::TripRetrieveResponse::Data

      def initialize:
        (data: Onebusaway::Models::TripRetrieveResponse::Data) -> void
        | (
          ?Onebusaway::Models::trip_retrieve_response
          | Onebusaway::BaseModel data
        ) -> void

      def to_hash: -> Onebusaway::Models::trip_retrieve_response

      type data =
        {
          entry: Onebusaway::Models::TripRetrieveResponse::Data::Entry,
          references: Onebusaway::Models::References
        }

      class Data < Onebusaway::BaseModel
        attr_accessor entry: Onebusaway::Models::TripRetrieveResponse::Data::Entry

        attr_accessor references: Onebusaway::Models::References

        def initialize:
          (
            entry: Onebusaway::Models::TripRetrieveResponse::Data::Entry,
            references: Onebusaway::Models::References
          ) -> void
          | (
            ?Onebusaway::Models::TripRetrieveResponse::data
            | Onebusaway::BaseModel data
          ) -> void

        def to_hash: -> Onebusaway::Models::TripRetrieveResponse::data

        type entry =
          {
            id: String,
            route_id: String,
            service_id: String,
            block_id: String,
            direction_id: String,
            peak_offpeak: Integer,
            route_short_name: String,
            shape_id: String,
            time_zone: String,
            trip_headsign: String,
            trip_short_name: String
          }

        class Entry < Onebusaway::BaseModel
          attr_accessor id: String

          attr_accessor route_id: String

          attr_accessor service_id: String

          attr_reader block_id: String?

          def block_id=: (String) -> void

          attr_reader direction_id: String?

          def direction_id=: (String) -> void

          attr_reader peak_offpeak: Integer?

          def peak_offpeak=: (Integer) -> void

          attr_reader route_short_name: String?

          def route_short_name=: (String) -> void

          attr_reader shape_id: String?

          def shape_id=: (String) -> void

          attr_reader time_zone: String?

          def time_zone=: (String) -> void

          attr_reader trip_headsign: String?

          def trip_headsign=: (String) -> void

          attr_reader trip_short_name: String?

          def trip_short_name=: (String) -> void

          def initialize:
            (
              id: String,
              route_id: String,
              service_id: String,
              block_id: String,
              direction_id: String,
              peak_offpeak: Integer,
              route_short_name: String,
              shape_id: String,
              time_zone: String,
              trip_headsign: String,
              trip_short_name: String
            ) -> void
            | (
              ?Onebusaway::Models::TripRetrieveResponse::Data::entry
              | Onebusaway::BaseModel data
            ) -> void

          def to_hash: -> Onebusaway::Models::TripRetrieveResponse::Data::entry
        end
      end
    end
  end
end
