module Onebusaway
  module Models
    type trip_detail_retrieve_params =
      {
        include_schedule: bool,
        include_status: bool,
        include_trip: bool,
        service_date: Integer,
        time: Integer
      }
      & Onebusaway::request_parameters

    class TripDetailRetrieveParams < Onebusaway::BaseModel
      extend Onebusaway::RequestParameters::Converter
      include Onebusaway::RequestParameters

      attr_reader include_schedule: bool?

      def include_schedule=: (bool) -> void

      attr_reader include_status: bool?

      def include_status=: (bool) -> void

      attr_reader include_trip: bool?

      def include_trip=: (bool) -> void

      attr_reader service_date: Integer?

      def service_date=: (Integer) -> void

      attr_reader time: Integer?

      def time=: (Integer) -> void

      def initialize:
        (
          include_schedule: bool,
          include_status: bool,
          include_trip: bool,
          service_date: Integer,
          time: Integer,
          request_options: Onebusaway::request_opts
        ) -> void
        | (
          ?Onebusaway::Models::trip_detail_retrieve_params
          | Onebusaway::BaseModel data
        ) -> void

      def to_hash: -> Onebusaway::Models::trip_detail_retrieve_params
    end
  end
end
