module Onebusaway
  module Models
    type vehicles_for_agency_list_response =
      { data: Onebusaway::Models::VehiclesForAgencyListResponse::Data }

    class VehiclesForAgencyListResponse < Onebusaway::Models::ResponseWrapper
      attr_accessor data: Onebusaway::Models::VehiclesForAgencyListResponse::Data

      def initialize:
        (data: Onebusaway::Models::VehiclesForAgencyListResponse::Data) -> void
        | (
          ?Onebusaway::Models::vehicles_for_agency_list_response
          | Onebusaway::BaseModel data
        ) -> void

      def to_hash: -> Onebusaway::Models::vehicles_for_agency_list_response

      type data =
        {
          limit_exceeded: bool,
          list: Array[Onebusaway::Models::VehiclesForAgencyListResponse::Data::List],
          references: Onebusaway::Models::References
        }

      class Data < Onebusaway::BaseModel
        attr_accessor limit_exceeded: bool

        attr_accessor list: Array[Onebusaway::Models::VehiclesForAgencyListResponse::Data::List]

        attr_accessor references: Onebusaway::Models::References

        def initialize:
          (
            limit_exceeded: bool,
            list: Array[Onebusaway::Models::VehiclesForAgencyListResponse::Data::List],
            references: Onebusaway::Models::References
          ) -> void
          | (
            ?Onebusaway::Models::VehiclesForAgencyListResponse::data
            | Onebusaway::BaseModel data
          ) -> void

        def to_hash: -> Onebusaway::Models::VehiclesForAgencyListResponse::data

        type list =
          {
            last_location_update_time: Integer,
            last_update_time: Integer,
            location: Onebusaway::Models::VehiclesForAgencyListResponse::Data::List::Location,
            trip_id: String,
            trip_status: Onebusaway::Models::VehiclesForAgencyListResponse::Data::List::TripStatus,
            vehicle_id: String,
            occupancy_capacity: Integer,
            occupancy_count: Integer,
            occupancy_status: String,
            phase: String,
            status: String
          }

        class List < Onebusaway::BaseModel
          attr_accessor last_location_update_time: Integer

          attr_accessor last_update_time: Integer

          attr_accessor location: Onebusaway::Models::VehiclesForAgencyListResponse::Data::List::Location

          attr_accessor trip_id: String

          attr_accessor trip_status: Onebusaway::Models::VehiclesForAgencyListResponse::Data::List::TripStatus

          attr_accessor vehicle_id: String

          attr_reader occupancy_capacity: Integer?

          def occupancy_capacity=: (Integer) -> void

          attr_reader occupancy_count: Integer?

          def occupancy_count=: (Integer) -> void

          attr_reader occupancy_status: String?

          def occupancy_status=: (String) -> void

          attr_reader phase: String?

          def phase=: (String) -> void

          attr_reader status: String?

          def status=: (String) -> void

          def initialize:
            (
              last_location_update_time: Integer,
              last_update_time: Integer,
              location: Onebusaway::Models::VehiclesForAgencyListResponse::Data::List::Location,
              trip_id: String,
              trip_status: Onebusaway::Models::VehiclesForAgencyListResponse::Data::List::TripStatus,
              vehicle_id: String,
              occupancy_capacity: Integer,
              occupancy_count: Integer,
              occupancy_status: String,
              phase: String,
              status: String
            ) -> void
            | (
              ?Onebusaway::Models::VehiclesForAgencyListResponse::Data::list
              | Onebusaway::BaseModel data
            ) -> void

          def to_hash: -> Onebusaway::Models::VehiclesForAgencyListResponse::Data::list

          type location = { lat: Float, lon: Float }

          class Location < Onebusaway::BaseModel
            attr_reader lat: Float?

            def lat=: (Float) -> void

            attr_reader lon: Float?

            def lon=: (Float) -> void

            def initialize:
              (lat: Float, lon: Float) -> void
              | (
                ?Onebusaway::Models::VehiclesForAgencyListResponse::Data::List::location
                | Onebusaway::BaseModel data
              ) -> void

            def to_hash: -> Onebusaway::Models::VehiclesForAgencyListResponse::Data::List::location
          end

          type trip_status =
            {
              active_trip_id: String,
              block_trip_sequence: Integer,
              closest_stop: String,
              distance_along_trip: Float,
              last_known_distance_along_trip: Float,
              last_location_update_time: Integer,
              last_update_time: Integer,
              occupancy_capacity: Integer,
              occupancy_count: Integer,
              occupancy_status: String,
              phase: String,
              predicted: bool,
              schedule_deviation: Integer,
              service_date: Integer,
              status: String,
              total_distance_along_trip: Float,
              closest_stop_time_offset: Integer,
              frequency: String,
              last_known_location: Onebusaway::Models::VehiclesForAgencyListResponse::Data::List::TripStatus::LastKnownLocation,
              last_known_orientation: Float,
              next_stop: String,
              next_stop_time_offset: Integer,
              orientation: Float,
              position: Onebusaway::Models::VehiclesForAgencyListResponse::Data::List::TripStatus::Position,
              scheduled_distance_along_trip: Float,
              situation_ids: Array[String],
              vehicle_id: String
            }

          class TripStatus < Onebusaway::BaseModel
            attr_accessor active_trip_id: String

            attr_accessor block_trip_sequence: Integer

            attr_accessor closest_stop: String

            attr_accessor distance_along_trip: Float

            attr_accessor last_known_distance_along_trip: Float

            attr_accessor last_location_update_time: Integer

            attr_accessor last_update_time: Integer

            attr_accessor occupancy_capacity: Integer

            attr_accessor occupancy_count: Integer

            attr_accessor occupancy_status: String

            attr_accessor phase: String

            attr_accessor predicted: bool

            attr_accessor schedule_deviation: Integer

            attr_accessor service_date: Integer

            attr_accessor status: String

            attr_accessor total_distance_along_trip: Float

            attr_reader closest_stop_time_offset: Integer?

            def closest_stop_time_offset=: (Integer) -> void

            attr_reader frequency: String?

            def frequency=: (String) -> void

            attr_reader last_known_location: Onebusaway::Models::VehiclesForAgencyListResponse::Data::List::TripStatus::LastKnownLocation?

            def last_known_location=: (
              Onebusaway::Models::VehiclesForAgencyListResponse::Data::List::TripStatus::LastKnownLocation
            ) -> void

            attr_reader last_known_orientation: Float?

            def last_known_orientation=: (Float) -> void

            attr_reader next_stop: String?

            def next_stop=: (String) -> void

            attr_reader next_stop_time_offset: Integer?

            def next_stop_time_offset=: (Integer) -> void

            attr_reader orientation: Float?

            def orientation=: (Float) -> void

            attr_reader position: Onebusaway::Models::VehiclesForAgencyListResponse::Data::List::TripStatus::Position?

            def position=: (
              Onebusaway::Models::VehiclesForAgencyListResponse::Data::List::TripStatus::Position
            ) -> void

            attr_reader scheduled_distance_along_trip: Float?

            def scheduled_distance_along_trip=: (Float) -> void

            attr_reader situation_ids: Array[String]?

            def situation_ids=: (Array[String]) -> void

            attr_reader vehicle_id: String?

            def vehicle_id=: (String) -> void

            def initialize:
              (
                active_trip_id: String,
                block_trip_sequence: Integer,
                closest_stop: String,
                distance_along_trip: Float,
                last_known_distance_along_trip: Float,
                last_location_update_time: Integer,
                last_update_time: Integer,
                occupancy_capacity: Integer,
                occupancy_count: Integer,
                occupancy_status: String,
                phase: String,
                predicted: bool,
                schedule_deviation: Integer,
                service_date: Integer,
                status: String,
                total_distance_along_trip: Float,
                closest_stop_time_offset: Integer,
                frequency: String,
                last_known_location: Onebusaway::Models::VehiclesForAgencyListResponse::Data::List::TripStatus::LastKnownLocation,
                last_known_orientation: Float,
                next_stop: String,
                next_stop_time_offset: Integer,
                orientation: Float,
                position: Onebusaway::Models::VehiclesForAgencyListResponse::Data::List::TripStatus::Position,
                scheduled_distance_along_trip: Float,
                situation_ids: Array[String],
                vehicle_id: String
              ) -> void
              | (
                ?Onebusaway::Models::VehiclesForAgencyListResponse::Data::List::trip_status
                | Onebusaway::BaseModel data
              ) -> void

            def to_hash: -> Onebusaway::Models::VehiclesForAgencyListResponse::Data::List::trip_status

            type last_known_location = { lat: Float, lon: Float }

            class LastKnownLocation < Onebusaway::BaseModel
              attr_reader lat: Float?

              def lat=: (Float) -> void

              attr_reader lon: Float?

              def lon=: (Float) -> void

              def initialize:
                (lat: Float, lon: Float) -> void
                | (
                  ?Onebusaway::Models::VehiclesForAgencyListResponse::Data::List::TripStatus::last_known_location
                  | Onebusaway::BaseModel data
                ) -> void

              def to_hash: -> Onebusaway::Models::VehiclesForAgencyListResponse::Data::List::TripStatus::last_known_location
            end

            type position = { lat: Float, lon: Float }

            class Position < Onebusaway::BaseModel
              attr_reader lat: Float?

              def lat=: (Float) -> void

              attr_reader lon: Float?

              def lon=: (Float) -> void

              def initialize:
                (lat: Float, lon: Float) -> void
                | (
                  ?Onebusaway::Models::VehiclesForAgencyListResponse::Data::List::TripStatus::position
                  | Onebusaway::BaseModel data
                ) -> void

              def to_hash: -> Onebusaway::Models::VehiclesForAgencyListResponse::Data::List::TripStatus::position
            end
          end
        end
      end
    end
  end
end
